.github/workflows/dev-worker-deploy.yml
.github/workflows/staging-worker-deploy.yml

- Add step to wait for tests to succeed before deploying workers

build: add wait-on-check action to worker deploys

---

app/models/people/person_payment.rb

- Fixes person payment currency call

fix: add to_sym to currency on person_payment

---

config/application.rb
spec/spec_helper.rb

- We need to use UTC-3 (Brasilia timezone) as the default timezone 

feature: use UTC-3 as default timezone

---

app/controllers/api/v1/integrations_controller.rb
spec/requests/api/v1/integrations_spec.rb

- We need to receive uuid as a parameter in the show method, in order to fetch integrations by uuid too
This is a temporary feature. We're looking forward to remove the numeric id, but before we need to talk about database rules

feature: receive id or uuid as a parameter in the show method

---

app/lib/web3/utils/cipher.rb

- To make it easier for developers and contributors to onboard, we are no longer using a robust SSL key for encryption, at least in the dev environment.

Chore: blank string as SSL key for development

---

app/models/non_profits/non_profit_impact.rb
spec/models/non_profit_impact_spec.rb

- Makes end date attribute optional for non profits impact

refactor: makes impact end date optional

---

.rubocop.yml
app/commands/donations/create_blockchain_donation.rb
app/commands/givings/community_treasure/add_balance.rb
app/commands/integrations/create_integration.rb
app/lib/web3/contracts/ribon_contract.rb
app/models/blockchain/chain.rb
app/models/blockchain/token.rb
spec/commands/donations/create_blockchain_donation_spec.rb
spec/commands/givings/community_treasure/add_balance_spec.rb
spec/lib/web3/contracts/ribon_contract_spec.rb
spec/models/chain_spec.rb

- Add decimals to ribon contract methods
This PR makes use of the token and pool models to correctly format the amount of decimals when requesting a donation / giving on the blockchain
- Create tokens in all envs (dev, staging and prod) [x]
- Create pools in all envs (dev, staging and prod) [x]

refactor: add donation_pool object as argument of ribon_contract methods

---

app/jobs/vouchers/webhook_job.rb
app/lib/currency/rates.rb
app/lib/request/api_request.rb
app/lib/web3/utils/fee.rb
app/lib/web3/utils/gas.rb
app/services/service/givings/fees/crypto/polygon_fee_calculator.rb
spec/jobs/vouchers/webhook_job_spec.rb
spec/lib/request/api_request_spec.rb

- Update RequestApi to return HTTParty response
We were parsing the response with RecursiveOpenStruct, but this ends up loosing some info of the HTTParty response such as the status, which we will need now.
Also, if the response was an HTML or nil, it would broke. In this way we always have the response as a json that HTTParty returns and we can use it normally.
- Test A

refactor: update RequestApi to return HTTParty response

---

config/initializers/rails_admin.rb

- This attribute is called background image on the model, but on rails admin it is called "support image". Since this was demanded by the staff, but can be confusing for developers, I left a comment to help looking for that on the future (and avoid spending time trying to make sense of it.

chore: comment to help finding this attribute

---

app/commands/donations/donate.rb
app/controllers/api/v1/vouchers/donations_controller.rb
spec/commands/donations/donate_spec.rb
spec/services/service/donations/statistics_spec.rb

- Add `skip_allowance` attribute to Donation Command to allow voucher donations, since they are always allowed by default, regarding the user that is using the voucher
- Test A

fix: add skip_allowance to Donation command to allow voucher donations

---

app/blueprints/person_payment_blueprint.rb
app/controllers/api/v1/person_payments_controller.rb

- This adds a big donations view for person payments so we can show the donations from big donors on the manager
- [#tech-468](https://ribon.atlassian.net/browse/TECH-468?atlOrigin=eyJpIjoiMzAyN2RhNGQwYjdhNGNmOTk3NDAxNGIzNTk4MDcyM2IiLCJwIjoiaiJ9)
- Try to make a request for person_payments/big_donors and check for blockchain_status and transaction_hash (if the person payment has a person blockchain transaction. if it doesn't, you'll have to link it)

feat: adds big donations view for person payments

---

app/models/users/user.rb
db/migrate/20230418154736_add_legacy_id_to_users.rb
db/schema.rb
spec/factories/users.rb
spec/models/user_spec.rb

- Now that we're making a web2 migration, we need to have access to the web2 id, so I added it as 'legacy id' here
- run db:migrate
- [#tech-421](https://ribon.atlassian.net/browse/TECH-421?atlOrigin=eyJpIjoiOGYyMmM3ZjA4MDZiNGI1Yzk2MDQwNGQ4ZDVkZTM2ZTciLCJwIjoiaiJ9)

feat: adds legacy_id on users table

---

app/commands/legacy/create_legacy_user_impact.rb

- Add a rescue if the logo is not attached
This will prevent the impact from not being saved. We can attach manually logos that eventually did not attach correctly
- Test A

fix: add rescue to non profit logo attaching in legacy

---

config/environments/production.rb

- Exclude healthcheck path from forced ssl
Elastic beanstalk is not able to healthcheck a path using ssl enforcment. We need this redirect
Our envs are currently on severe because the health check cannot complete (dev now is OK with this PR), but they are working just fine
- Test A

build: update ssl options to health check

---

app/models/concerns/authenticatable_model.rb

- Refactor token issue at to be referent to the first refresh token
The authenticatable can have multiple refresh tokens (for example, it logs in from web and from a mobile app). In this case, both should be valid, having as reference the first refresh token date
- Test A

refactor: update token issued at to get first token from authenticatable

---

app/commands/contributions/increase_contribution_balance_fee.rb
app/services/service/contributions/contribution_fee_delete_service.rb
spec/commands/contributions/increase_contribution_balance_fee_spec.rb
spec/factories/contribution_fees.rb
spec/services/service/contributions/contribution_fee_delete_service_spec.rb

- this service is necessary because we need to delete a contribution fee and create a new one so our database is equal to what happened on blockchain. Contribution 514 was supposed to be created before contribution 505.
- Test A

fix: add service to delete contribution_fee

---

app/lib/payment/gateways/stripe/entities/customer.rb
spec/lib/payment/gateways/stripe/entities/customer_spec.rb

- Add default address to stripe
This will allow us to not ask for the address of the user.
We discussed with the financial team and that is not needed to make the fiscal notes
- Test A

feat: add default address to stripe

---

app/controllers/api/v1/news/articles_controller.rb
config/routes.rb

- Adds a method to filter the news for only showing the articles created after the user was created
- [#prod3-127](https://ribon.atlassian.net/browse/PROD3-127?atlOrigin=eyJpIjoiZTU1NzhkN2VkOTAzNDUwMGJmYmE0MjEwY2ViODE0ZjIiLCJwIjoiaiJ9)
- Try with users created at different days

feat: adds articles_since_user_creation method

---

app/models/configs/ribon_config.rb
app/models/contributions/contribution.rb
app/queries/contribution_queries.rb
app/services/service/contributions/fees_labeling_service.rb
app/services/service/contributions/ticket_labeling_service.rb
config/initializers/rails_admin.rb
db/migrate/20231018165918_add_disable_labeling_to_ribon_configs.rb
db/schema.rb
spec/factories/ribon_configs.rb
spec/models/ribon_config_spec.rb
spec/services/service/contributions/fees_labeling_service_spec.rb

- Update labeling to get cause instead of receiver
This is needed since non profits contributions can charge fees for the cause related to the non profit

fix: update labeling to get cause instead of receiver

---

app/commands/tickets/collect_and_donate_by_external_ids.rb
app/commands/tickets/collect_and_donate_by_integration.rb

- enables donation if user has tickets when logging mid donation
- logout from an account that has more than one tickets, try to donate by login in via magic link

fix: enables donation if user has tickets

---

app/jobs/events/donations/send_donation_event_job.rb

Handles donation event for no profits with less than one impact_by_ticket so it won't raise "Impact can't be zero"

fix: fx donation event job for np with < 1 impact

---

app/commands/users/reset_donation_streak.rb
app/jobs/users/reset_donation_streak_job.rb
app/workers/users/reset_donation_streak_worker.rb
app/workers/users/reset_everyone_donation_streak_worker.rb
spec/commands/users/reset_donation_streak_spec.rb
spec/jobs/users/reset_donation_streak_job_spec.rb
spec/workers/users/reset_donation_streak_worker_spec.rb
spec/workers/users/reset_everyone_donation_streak_worker_spec.rb

- allow command to reset all user donation stats at once
- Test A

fix: allow command to reset all user donation stats at once

---

app/jobs/events/club/send_inactivated_club_event_job.rb
app/observers/subscription_observer.rb
spec/jobs/events/club/send_inactivated_club_event_job_spec.rb

- Sends the club event with the pix_club_inactivated type so that customer.io can send the email 
- No

feat: adds send inactivated club event

---

app/blueprints/legacy_non_profit_blueprint.rb

The legacy non profit logos where coming with a black square surrounding them. Because we were using jpg instead of png

fix: legacy non profit logo transparency

---

app/commands/auth/accounts/send_otp_email.rb
app/controllers/users/v1/authentication_controller.rb
spec/requests/users/v1/authentication_spec.rb

- Send back the account id when a OTP e-mail is sent.

feat: return account id when sending an OTP email

---

app/commands/givings/subscriptions/create_direct_transfer_subscription.rb
spec/requests/managers/v1/subscriptions_spec.rb

- Fixes existing subscription verification so we can create direct_transfer subscriptions even for existing subscribers

fix: fixes direct_transfer subscription constraint
