RibonDAO/core-api

.gitignore
config/environments/production.rb
config/storage.yml

- Add digital ocean space
- change env vars

build: add digital ocean space to storage.yml

---

.rubocop.yml
Gemfile
Gemfile.lock
app/lib/simple_command.rb
app/lib/simple_command/errors.rb

refactor: add simple command to lib

---

app/commands/donations/donate.rb
spec/commands/donations/donate_spec.rb

- Adds donation blockchain link to Donation model

refactor: add DEFAULT_DONATION_AMOUNT and donation blockchain link

---

.ebextensions/securelistener-clb.config

build: add securelistener-clb config to ebextensions

---

app/controllers/api/v1/users_controller.rb
config/routes.rb
spec/requests/api/v1/users_spec.rb

feat: add search route to users

---

app/blueprints/user_impact_blueprint.rb
app/controllers/api/v1/users_controller.rb
app/models/user.rb
app/services/user_impacts/user_impact.rb
config/routes.rb

- Change in the return of the impact

fix: add route to user impact

---

app/controllers/api/v1/users_controller.rb

fix: update User in userimpact controller to test

---

Gemfile
Gemfile.lock
app/assets/config/manifest.js
config/routes.rb

Graphiql was causing some troubles in deploy and was not being used
- Remove graphiql

fix: remove graphiql

---

db/migrate/20220222123150_create_users.rb

- Uncomment create users migration

fix: uncomment create users migration

---

app/controllers/api/v1/users/impacts_controller.rb
config/routes.rb
spec/requests/api/v1/users/impacts_spec.rb

feat: add donations_count to users impact controller

---

Gemfile
Gemfile.lock

- Add ffi gem to fix error on bundle install in aws

build: add ffi gem

---

.ebextensions/packages.config

- Add libffi-dev install to aws

build: add libffi-dev install

---

.ebextensions/packages.config

- Add libxml2-dev to packages config

build: add libxml2-dev to packages.config

---

README.md

- Add new readme with install instructions
- Add new infos about the environments

docs: update readme with install instructions and envs

---

app/blueprints/non_profit_blueprint.rb
db/migrate/20220428143225_add_description_to_non_profits.rb
db/schema.rb
spec/requests/api/v1/non_profits_spec.rb

- Add description to non profits

feat: add description to non profits

---

app/models/non_profit.rb

- Add description to translated fields

feat: add description to translated fields in NonProfit

---

app/services/user_services/user_impact.rb
spec/factories/non_profits.rb

- Fix usd cents convert in `user_impact`

fix: update user_impact service to use cents

---

app/commands/donations/donate.rb
db/migrate/20220509182906_add_value_to_donations.rb
db/schema.rb
spec/commands/donations/donate_spec.rb

feat: add value to donation

---

app/services/giving_services/fees/crypto/polygon_fee_calculator_service.rb
app/services/giving_services/fees/fee_calculator_service.rb
config/env.yml
spec/services/giving_services/fees/crypto/polygon_fee_calculator_service_spec.rb
spec/support/stub_helpers.rb
spec/support/vcr_cassettes/polygon_gas_fee_request.yml

- Add polygon fee calculator
- Add route to get fees

feat: add Crypto PolygonFeeCalculatorService

---

.github/workflows/tests.yml
spec/services/user_services/user_impact_spec.rb
spec/spec_helper.rb

build: add minimum coverage to ci

---

Gemfile
Gemfile.lock
app/lib/payment/stripe/base.rb
config/env.yml

feat: add Stripe and Stripe configs

---

app/lib/payment/stripe/base.rb
app/lib/payment/stripe/entities/customer.rb
app/models/concerns/uuid_helper.rb
app/models/customers/customer.rb
db/migrate/20220614153906_create_uuid_extension.rb
db/migrate/20220614153943_create_customers.rb
db/schema.rb
spec/factories/customers.rb
spec/lib/payment/stripe/entities/customer_spec.rb

- Here we need to create the basis of our stripe integration, by creating Stripe customers using our integration

Feat: Creating and persisting Stripe customers

---

.github/workflows/tests.yml
app/controllers/main_controller.rb
config/routes.rb
spec/requests/main_spec.rb

- Add a health check path
This is necessary for health checks in aws

feat: add health check path

---

config/env.yml

- Add stripe env vars to env.yml
- Add production env vars in the production environment

feat: add STRIPE env vars to env.yml

---

app/adapters/adapter/controllers/payment/credit_cards.rb
app/controllers/api/v1/payments/credit_cards_controller.rb

- Refactor credit cards adapter

refactor: update credit cards adapter to a class

---

.github/workflows/staging-worker-deploy.yml

- Add staging action to deploy worker

build: add staging-worker-deploy action

---

app/models/users/user.rb
app/services/user_services/user_impact.rb
spec/factories/non_profits.rb
spec/models/user_spec.rb
spec/services/user_services/user_impact_spec.rb

- Refactor user impact to use api data

refactor: update user_services user_impact to use api data

---

app/controllers/api/v1/integrations_controller.rb
config/routes.rb
spec/requests/api/v1/integrations_spec.rb

- Adds integration update method, route and tests

feat: adds update integration route

---

app/blueprints/user_blueprint.rb
app/controllers/api/v1/users_controller.rb
spec/requests/api/v1/users_spec.rb

- If a user had donated and then opened the app in a new window with no cache info, the button would show that the user had tickets but he did not. So now the interface has this info and can show the right message on the button.

fix: added last_donation_at on UserBlueprint to solve cache problem

---

.rubocop.yml
app/commands/donations/donate.rb
app/lib/web3/contracts/ribon_contract.rb
app/models/integrations/integration_wallet.rb
spec/commands/donations/donate_spec.rb
spec/factories/integration_wallets.rb
spec/lib/web3/contracts/ribon_contract_spec.rb
spec/models/integration_wallet_spec.rb

- Add integration key to blockchain donation request

Add integration key to blockchain donation request

---

config/initializers/rails_admin.rb

feat: add DonationBlockchainTransaction and Chain to rails admin

---

app/jobs/donations/update_donation_blockchain_transaction_status_job.rb
app/lib/web3/utils/transaction_utils.rb
app/models/donations/donation_blockchain_transaction.rb
app/services/person_payment_services/blockchain_transaction.rb
app/services/service/donations/donation_blockchain_transaction.rb
spec/jobs/donations/update_donation_blockchain_transaction_status_job_spec.rb
spec/lib/web3/utils/transaction_utils_spec.rb
spec/services/service/donations/donation_blockchain_transaction_spec.rb
spec/spec_helper.rb

- Add services to donation blockchain transaction
- Refactor status fetch from blockchain
- Add job to update donation blockchain transaction status

Donation Blockchain Transaction status update from blockchain

---

app/commands/application_command.rb

- Add reporter log to ApplicationCommand exception handle

feat: add Reporter log to ApplicationCommand

---

app/commands/givings/card/calculate_card_giving.rb
spec/commands/givings/card/calculate_card_giving_spec.rb

- Hotfix in calculate card fees

fix: remove service fees duplicated on CalculateCardGiving

---

app/models/non_profits/non_profit_impact.rb

fix: remove impact by ticket float conversion

---

app/controllers/main_controller.rb

- We need to standartize the response type for all the application resources in the health check endpoint

refactor: same response type to all resources

---

db/seeds.rb

- Some integration seeds are broken and we need to fix it

fix: db seeds

---

app/controllers/api/v1/users_controller.rb
app/models/users/user_donation_stats.rb
config/routes.rb
spec/models/user_donation_stats_spec.rb
spec/rails_helper.rb
spec/requests/api/v1/users_spec.rb
spec/support/time_helpers.rb

- Refactor last donation at
- Add TimeHelpers to tests

refactor: add integration to last_donation_at on UserDonationStats

---

.github/workflows/tests.yml

- add seed test to github flow

fix: add seed test to github flow

---

.github/workflows/production-worker-deploy.yml

- Add production worker deploy to github workflows

feat: add production-worker-deploy.yml to github workflows

---

app/blueprints/non_profit_blueprint.rb
db/migrate/20220830112145_remove_link_and_description_from_non_profits.rb
db/schema.rb
spec/factories/non_profits.rb
spec/requests/api/v1/non_profits_spec.rb

- Removes columns link and description from non_profits table

refactor: remove link/description from nonprofit

---

app/lib/payment/gateways/stripe/payment_processor.rb

- Add id customer from stripe in customer_keys column

feat: add stripe customer id in customer table

---

app/services/graphql/queries/fetch_donation_balances.rb

- adjust the graph query to handle entity relationships 
- No.

fix: adjust the graph query

---

.github/workflows/production-worker-deploy.yml
.rubocop.yml
app/controllers/api/v1/users_controller.rb
app/models/integrations/integration.rb
lib/ext/string.rb
spec/models/integration_spec.rb

- Fix can donate query to find integration by unique address

feat: add #find_by_id_or_unique_address to Integration

---

app/controllers/api/v1/givings/user_givings_controller.rb

fix: add safe operator to users givings controller

---

app/commands/donations/create_blockchain_donation.rb
spec/commands/donations/create_blockchain_donation_spec.rb

- Refactor donate command to use the CreateBlockchainDonation command
This new command will be used in the new retry logic of creating a donation in the blockchain

feat: add CreateBlockchainDonation command

---

app/commands/donations/create_blockchain_donation.rb
app/commands/donations/donate.rb
app/controllers/api/v1/donations_controller.rb
app/jobs/donations/create_blockchain_donation_job.rb
config/initializers/sidekiq.rb
spec/commands/donations/donate_spec.rb
spec/jobs/donations/create_blockchain_donation_job_spec.rb
spec/requests/api/v1/donations_spec.rb

- Add CreateBlockchainDonation to donation flow
- Mechanism to retry the donation on the blockchain if it fails

refactor: add CreateBlockchainDonation command call to Donate command

---

app/models/payment/methods/credit_card.rb

fix: update credit card #from syntax

---

README.md
script.sh

- script to run dev environment

feat: script to run dev environment

---

config/initializers/rails_admin.rb

- add wallet address to non profits admin

fix: add wallet address to non profits admin

---

app/blueprints/cause_blueprint.rb
app/blueprints/non_profit_blueprint.rb
spec/requests/api/v1/non_profits_spec.rb

- Add cause blueprint
- Add cause to non profits response

feat: add CauseBlueprint and cause to non profits

---

app/services/user_services/user_impact.rb

fix: add to_i for user impact

---

app/blueprints/integration_blueprint.rb
spec/requests/api/v1/integrations_spec.rb

- Adds webhook_url to integrations blueprint so we can get it on front end

feat: adds webhook_url to integrations blueprint

---

app/blueprints/customer_blueprint.rb
app/blueprints/person_blueprint.rb
app/blueprints/person_payment_blueprint.rb
app/controllers/api/v1/person_payments_controller.rb
config/routes.rb
db/schema.rb

- Creating route to get all PersonPayments, so that we can show it in dapp manager

feat: add PersonPayment request

---

Gemfile
Gemfile.lock
app/blueprints/person_payment_blueprint.rb
app/controllers/api/v1/person_payments_controller.rb
config/initializers/kaminari_config.rb
spec/requests/api/v1/person_payments_spec.rb

- Adding pagination attributes to PersonPayments

feat: add pagination to PersonPayment

---

app/controllers/api/v1/person_payments_controller.rb
config/initializers/kaminari_config.rb

- Changing per_page to 50, in the PersonPayment pages

fix: update per_page number

---

app/blueprints/person_payment_blueprint.rb
app/commands/givings/payment/credit_card_refund.rb
app/models/people/person_payment.rb
db/migrate/20221025133106_add_refund_date_to_person_payments.rb
db/schema.rb
spec/commands/givings/payment/credit_card_refund_spec.rb
spec/factories/payment/person_payments.rb
spec/models/person_payment_spec.rb
spec/support/vcr_cassettes/stripe_payment_method.yml

- Register refund_date when the payment was refunded
- Update refund_date when return refund return success
- closes [#TECH-101](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26?modal=detail&selectedIssue=TECH-101)
- Made a refund and verify if has a refund_date

(TECH-101) Register refund date on db

---

app/controllers/api/v1/givings/user_givings_controller.rb

- We are going to show refunded payments on giving cards
- Test A

TECH-102: show refunded payments on frontend

---

app/models/stories/story.rb

- Adds i18n to some story fields
- Test A

feat: dapp-576

---

app/commands/givings/payment/order_types/credit_card.rb
app/models/integrations/integration.rb
app/models/people/person_payment.rb
db/migrate/20221101135938_change_integration_id_from_person_payment.rb
db/schema.rb
spec/commands/givings/payment/create_order_spec.rb
spec/factories/payment/person_payments.rb

- the frontend passes the uuid of the integration and we were trying to save in a bigint field, so I decided to add the integration relation in the person payment
- Make a contribution and see if the integration field is updated correctly

TECH-151: added integration on person payment

---

app/blueprints/cause_blueprint.rb
app/models/causes/cause.rb
spec/requests/api/v1/causes_spec.rb

- Add a cover image to the causes modal, in order to use it in the support cause page

chore: append cover image to cause

---

db/migrate/20221101173448_add_cause_references_to_pool.rb

- delete null false from cause and pool relation

chore: delete null false from cause and pool relation

---

app/blueprints/voucher_blueprint.rb
db/schema.rb

- Vouchers displayed by the webhook had some fields that were not needed (integration and updated at)
- Removes integration and updated at on the voucher rendering
- [Dapp-555] (https://ribon.atlassian.net/browse/DAPP-555)
- open rails console and create a voucher, then open rails console and anter `JSON.parse(VoucherBlueprint.render(Voucher.first))`

refactor: removes unnecessary fields

---

app/blueprints/non_profit_blueprint.rb
app/blueprints/story_blueprint.rb

- Add quality to image variants
This is necessary so the images dont loose quality
- Test A

fix: update variant qualities on non_profit and stories blueprint

---

app/commands/givings/community_treasure/add_balance.rb
app/commands/givings/payment/create_order.rb
app/commands/givings/payment/order_types/credit_card.rb
app/commands/givings/payment/order_types/cryptocurrency.rb
app/controllers/api/v1/payments/credit_cards_controller.rb
app/jobs/givings/payment/add_giving_to_blockchain_job.rb
app/models/causes/cause.rb
spec/commands/givings/payment/create_order_spec.rb
spec/jobs/givings/payment/add_giving_to_blockchain_job_spec.rb
spec/models/cause_spec.rb
spec/requests/api/v1/payments/credit_cards_spec.rb

- Update contribution flow to accept a cause param
- If the cause param is present, add the balance on blockchain to the correct pool
- Refactor Order creation according to payment type
- Make a contribution to a cause and check if its pool increased the value

refactor: add cause to CreditCard order and pool to AddBlockchain

---

app/commands/donations/create_blockchain_donation.rb
spec/commands/donations/create_blockchain_donation_spec.rb

- Add logic to send the pool on free donations
- Test A

feat: add default cause pool to CreateBlockchainDonation

---

app/blueprints/cause_blueprint.rb
app/blueprints/pool_blueprint.rb
app/blueprints/token_blueprint.rb
app/controllers/api/v1/causes_controller.rb
config/routes.rb
spec/requests/api/v1/causes_spec.rb

- Adjust of blueprint to return pool, token in causes and route to show single cause
- Add association with pools in cause blueprint
- blueprints to pool and token to return to front
- route and function show an single cause on cause controller 
- test to function show
- eg: closes [#TECH-139](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26?modal=detail&selectedIssue=TECH-139)
- Test A

(TECH-139) Cause details

---

app/blueprints/non_profit_blueprint.rb
app/models/non_profits/non_profit.rb
spec/requests/api/v1/non_profits_spec.rb

- Remove description (NOT impact description) and cover image from Non Profit
Requested by @luizabrito-pm 
- Test A

feat: remove unused fields

---

app/blueprints/guest_blueprint.rb
app/blueprints/person_blueprint.rb

- Show wallet address when is crypto payment
- Add guest on blueprint
- closes [#TECH-156](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26/backlog?view=detail&selectedIssue=TECH-156&issueLimit=100)

(TECH-156) Show wallet address when is crypto payment

---

app/blueprints/non_profit_blueprint.rb
db/schema.rb
spec/requests/api/v1/non_profits_spec.rb

- Adding status top NonProfit blueprint

feat: add status top NonProfit blueprint

---

app/commands/non_profits/create_non_profit.rb
app/commands/non_profits/update_non_profit.rb
app/controllers/api/v1/non_profits_controller.rb
app/models/blockchain/pool.rb
config/routes.rb
spec/factories/pools.rb
spec/models/pool_spec.rb
spec/requests/api/v1/non_profits_spec.rb

- Adding create, show and update methods to NonProfits

feat: Add create, show and update to NonProfits

---

app/commands/donations/update_failed_donations.rb
spec/commands/donations/update_failed_donations_spec.rb

- Fix failed donations
- Test A

fix: update failed_transactions count

---

.github/workflows/dev-deploy.yml
.github/workflows/test-deploy.yml
.github/workflows/tests.yml

- When a PR to staging is created the test branch is updated with the new branch from the PR
- Test A

Fix: New github action to test the new flow

---

app/controllers/api/v1/integrations_controller.rb

-  integration order by created at desc
- manager: integrations section

TECH-148 -  Integration order by created at desc

---

.github/workflows/test-deploy.yml

TECH-178: update test flow

---

app/blueprints/cause_blueprint.rb
app/blueprints/non_profit_blueprint.rb
spec/requests/api/v1/causes_spec.rb

- Add non profits on cause blueprint
- Add non profits on cause blueprint
- eg: closes [#TECH-158](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26?modal=detail&selectedIssue=TECH-158)

(TECH-158) Add non profits on cause blueprint

---

app/controllers/api/v1/non_profits_controller.rb
app/models/blockchain/pool.rb
db/schema.rb
spec/factories/pools.rb
spec/models/pool_spec.rb

- We need to order the non profits by cause
- No.

feat: adds order non profits by cause

---

app/blueprints/non_profit_blueprint.rb
app/blueprints/non_profit_impacts_blueprint.rb
spec/requests/api/v1/non_profits_spec.rb

- Add Impacts Page on manager
- Created blueprint to non profit impacts
- Add non profit impacts on non profit blueprint
- eg: closes [#TECH-75](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26?modal=detail&selectedIssue=TECH-75)

(TECH-75): Impacts Page

---

.github/workflows/deploy.yml
.github/workflows/test-deploy.yml

- new flow making staging the default branch
- Update staging with develop
- Make staging the default branch
- update env from dapp-staging and dapp-manager-staging to point to core-api-dev
- Test A

fix: new flow making staging the default branch

---

app/controllers/integrations/v1/impacts_controller.rb
config/routes.rb
spec/requests/integrations/v1/impacts_spec.rb

- Add impacts route to integrations
- Test A

feat: add impacts controller to integrations

---

app/blueprints/integration_impact_blueprint.rb
app/controllers/api/v1/integrations/impacts_controller.rb
app/services/service/donations/statistics.rb
spec/requests/api/v1/integrations/impacts_spec.rb

- Add IntegrationImpact blueprint
This is needed in order to the request return the non profit data
- Test A

feat: add IntegrationImpact blueprint

---

app/blueprints/history_blueprint.rb
app/controllers/api/v1/site/histories_controller.rb
app/models/history.rb
config/initializers/rails_admin.rb
config/routes.rb
db/migrate/20221220150049_create_history.rb
db/schema.rb
spec/factories/histories.rb
spec/models/history_spec.rb
spec/requests/api/v1/site/histories_spec.rb

- We need to create a table with history of total donations and donors of web2 and web3 to the site
- Create table History
- Add controller and blueprint
- Tests
- eg: closes [#TECH-214](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26?modal=detail&selectedIssue=TECH-214)
- Verify if history appear on rails admin and add total donors and donations

(TECH-214) Table with history of web2 and web3

---

app/services/graphql/queries/fetch_donation_balances.rb

- As we add donation batches, the user is no longer sent in the donation balance query

feat: update donation balances the_graph query

---

app/lib/web3/providers/networks.rb

- update network with new contract
- Test A

fix: update network with new contract

---

app/blueprints/history_blueprint.rb
app/controllers/api/v1/site/histories_controller.rb
app/models/history.rb
spec/requests/api/v1/site/histories_spec.rb

- Route to show total donations to web2 and web3 to new site
- Route and controller to total donations
- Functions to convert values
- Adjust test
- eg: closes [#TECH-211](https://ribon.atlassian.net/jira/software/c/projects/TECH/boards/26?modal=detail&selectedIssue=TECH-265)

(TECH-211) Route to total donations

---

app/blueprints/integration_blueprint.rb
app/models/integrations/integration.rb
config/env.yml
spec/models/integration_spec.rb
spec/requests/api/v1/integrations_spec.rb

- Add link to integration dashboard address to show on manager
Add base url to dashboard on env
- Add integration dashboard address on blueprint and model
- eg: closes [#DAPP-624](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-624)

(DAPP-624) Add link to integration dashboard address

---

app/services/service/donations/balance_history.rb

- fix person payment without receiver
- Test A

Tech 204: fix person payment without receiver

---

app/commands/donations/create_blockchain_donation.rb
spec/commands/donations/create_blockchain_donation_spec.rb

- fix for passing user email hash on donation blockchain transaction, instead of user email
- Test A

Tech 263: fix for making donation blockchain transaction work again

---

app/controllers/api/v1/site/histories_controller.rb
app/controllers/api/v1/site/site_controller.rb
spec/requests/api/v1/site/histories_spec.rb
spec/requests/api/v1/site/site_spec.rb

- round total amount for site routes
- Test A

Fix: round total amount for site routes

---

app/controllers/api/v1/non_profits_controller.rb

- add background image to non profit params to fix the create/update non profit on manager
- Test A

Tech 260: add background image to non profit params

---

app/blueprints/non_profit_blueprint.rb
app/models/non_profits/non_profit.rb

move switch logic to blueprint instead of model, in order to make our rake task work again
- Test A

HOTFIX: move switch logic to blueprint (related to dapp-659)

---

app/blueprints/non_profit_impacts_blueprint.rb
app/models/non_profits/non_profit_impact.rb
db/migrate/20230118112725_add_donor_recipient_to_non_profit_impacts.rb
db/schema.rb
spec/factories/non_profit_impacts.rb
spec/factories/non_profits.rb
spec/models/non_profit_impact_spec.rb

- Add donor recipient to non profit impacts
- Add column donor recipient to non profit impacts table
- Adjust tests
- Adjust model
- Adjust factories
- eg: closes [#DAPP-630](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-630)

(DAPP-630) Add donor recipient to non profit impacts

---

app/blueprints/non_profit_impacts_blueprint.rb

- add impact description to NonProfit impact blueprint
- Test A

feat: add impact description to NonProfit impact blueprint

---

app/controllers/api/v1/non_profits_controller.rb

- Allow non profit impacts params
- Test A

feat: permit non profit impacts params

---

app/models/non_profits/non_profit.rb

- Accept nested atributes for non profit impacts
- Test A

feat: accept nested atributes for non profit impacts

---

app/controllers/api/v1/non_profits_controller.rb
app/models/non_profits/non_profit.rb
spec/models/non_profit_spec.rb

- remove validate of impact_description from non_profits

remove validate of impact_description from non_profits

---

app/controllers/api/v1/causes_controller.rb

- Adds main and cover image to cause params in order to be able to upload it

feat: adds cover and main image to cause params

---

app/controllers/api/v1/site/histories_controller.rb
app/controllers/api/v1/site/site_controller.rb
spec/requests/api/v1/site/histories_spec.rb

- big numbers with delimiter on site routes
- https://dapp-dev-api.ribon.io/api/v1/site/total_donors
- https://dapp-dev-api.ribon.io/api/v1/site/total_donors?language=pt-BR

fix: big numbers with delimiter on site routes

---

app/lib/web3/utils/gas.rb

- changed gas limit because the transactions failed(https://polygonscan.com/tx/0x0e39155f7b4b02ecbce8412e5f213231f106b6a13b25e7a070989d25e28b6cfd)
- Test A

fix: new gas limit

---

app/commands/person_payments/blockchain_transactions/update_api_only_transactions.rb
app/commands/person_payments/blockchain_transactions/update_failed_transactions.rb
spec/commands/person_payments/blockchain_transactions/update_api_only_transactions_spec.rb
spec/commands/person_payments/blockchain_transactions/update_failed_transactions_spec.rb

- i forgot to add the status on query
- Test A

fix: retry only paid person payments

---

app/commands/givings/payment/order_types/cryptocurrency.rb
app/controllers/api/v1/payments/cryptocurrency_controller.rb
config/routes.rb
spec/requests/api/v1/person_payments_spec.rb

- Adds cause/non profit to cryptocurrency controller
- Adjust person payment routes
- No.

feat: adds crypto receiver

---

app/blueprints/person_payment_blueprint.rb
app/models/people/person_payment.rb
spec/requests/api/v1/person_payments_spec.rb

- Adds service fees to person payment blueprint
- No.

feat: renders service fees

---

.github/workflows/dev-worker-deploy.yml
.github/workflows/test-deploy.yml

- Deploy develop app after merge
- I wanted to make a push to trigger the dev-worker-deploy, but did not worked, I would have to make a commit and then a push, so I transfer the steps from the other workflow to this one
- Test A

fix: deploy develop app after merge

---

app/lib/web3/utils/gas.rb

-  increase gas fee according with https://polygonscan.com/gastracker
- Test A

fix: increase gas fee

---

.rubocop.yml
Gemfile
Gemfile.lock
app/lib/ribon_mailer.rb
app/mailers/sendgrid_web_mailer.rb
config/env.yml

- copy from old api the sendgrid config.
- add sengrid key on aws
- Test A

Tech 201: sendgrid config

---

.rubocop.yml
app/controllers/api/v1/users_controller.rb
app/controllers/application_controller.rb
app/models/users/user.rb
db/migrate/20230213163444_add_language_to_user.rb
db/schema.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/requests/api/v1/users_spec.rb

- added language to user because of emails. We need to know the language to send them.
- Test A

Tech 252: added language to user

---

app/lib/web3/utils/gas.rb

- It's only for test one blockchain transaction, i won't run all of them with this fee
- Test A

fix: update gas fee

---

.rubocop.yml
app/lib/date_range/splitter.rb
app/services/service/donations/statistics.rb
app/services/service/integrations/impact.rb

- When doens't have donations or impacts some functions to calculate returns error 500 and in the dashboard still in loop 

fix: validations on impacts

---

app/lib/web3/utils/gas.rb

- update default max fee per gas
- Test A

fix: default max fee per gas

---

app/controllers/api/v1/news/authors_controller.rb
spec/requests/api/v1/news/authors_spec.rb

fix required payload when creates/updates an author
- Test A

fix: author payload

---

spec/requests/api/v1/news/authors_spec.rb

hotfix: use curly braces for authors payload

---

config/initializers/rails_admin.rb

add author and article resources to rails admin, in order to test it before add to manager

feat: add author and articles to rails admin

---

app/blueprints/article_blueprint.rb
app/lib/formatters/date.rb
config/locales/en.yml
config/locales/pt-BR.yml
spec/lib/formatters/date_spec.rb

- Stop on weeks
- Don't use ActionView as dependency
- Add a not publised yet handler to the blueprint

refactor: use pure ruby to do the humanization

---

app/jobs/mailers/send_person_payment_email_job.rb
spec/jobs/mailers/send_person_payment_email_job_spec.rb

- Adjust the impact for contribution to non profit
- Test A

fix: email with the correct impact for non profit

---

app/models/big_donor.rb
app/models/users/user.rb
db/migrate/20230309120616_create_big_donors.rb
db/schema.rb
spec/factories/big_donors.rb
spec/models/big_donor_spec.rb
spec/models/user_spec.rb

feat: add BigDonor table

---

app/models/contribution.rb
app/models/people/person_payment.rb
app/models/users/user_donation_stats.rb
db/migrate/20230309142312_create_contributions.rb
db/migrate/20230309144900_add_fields_to_person_payments.rb
db/migrate/20230309151101_add_person_payments_to_contributions.rb
db/schema.rb
spec/factories/contributions.rb
spec/factories/user_donation_stats.rb
spec/factories/user_managers.rb
spec/factories/users.rb
spec/models/contribution_spec.rb
spec/models/person_payment_spec.rb
spec/models/user_donation_stats_spec.rb

- Add Contribution table and it's relation with PersonPayment

feat: add Contribution table

---

app/models/configs/ribon_config.rb
app/models/contributions/contribution.rb
app/models/contributions/contribution_balance.rb
config/initializers/rails_admin.rb
db/migrate/20230309194146_create_contribution_balances.rb
db/migrate/20230309195215_add_contribution_fee_percentage_to_ribon_configs.rb
db/schema.rb
spec/factories/contribution_balances.rb
spec/factories/ribon_configs.rb
spec/models/contribution_balance_spec.rb
spec/models/contribution_spec.rb
spec/models/ribon_config_spec.rb

- Add Contribution Balance model
- Add configuration to tickets / fees percentage on contribution balance
- Test A

feat: add ContributionBalance model

---

spec/lib/formatters/date_spec.rb

- Fix Formatters::Date tests
- Test A

fix: mock Time.zone.now on Formatters::Date spec

---

app/controllers/api/v1/givings/offers_controller.rb
db/schema.rb
spec/factories/ribon_configs.rb
spec/factories/users.rb
spec/models/ribon_config_spec.rb

-  add subscription on offer params permit
- eg: closes [#DAPP-733](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-733)

fix: add subscription on offer params permit

---

spec/services/service/users/statistics_spec.rb

- Fix statistics spec
- Test A

fix: update statistics spec

---

db/seeds.rb
spec/db/seeds_spec.rb

- Adds new seeds for other factories and tests them
- Run the seeds or tests

chore: adds new seeds and tests

---

app/models/blockchain/pool.rb
app/models/donations/donation_blockchain_transaction.rb
app/models/users/user.rb
app/models/users/user_donation_stats.rb
spec/factories/donation_blockchain_transactions.rb
spec/factories/donations.rb
spec/factories/pools.rb
spec/factories/user_donation_stats.rb
spec/models/crypto_user_spec.rb
spec/models/donation_blockchain_transaction_spec.rb
spec/models/pool_spec.rb
spec/models/user_donation_stats_spec.rb
spec/models/user_spec.rb

- Add condition to permit another donation if is the first on native
- eg: closes [#DAPP-704](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-704)

[DAPP-704] Permit another donation on native 

---

app/controllers/api/v1/person_payments_controller.rb
app/services/service/users/statistics.rb
spec/requests/api/v1/person_payments_spec.rb

- Fix total donated for causes and non profits based on only paid payments
- Test A

fix: update statistics to get only paid payments

---

app/blueprints/article_blueprint.rb
app/controllers/api/v1/news/articles_controller.rb
app/models/article.rb
db/migrate/20230330173345_add_language_to_articles.rb
db/schema.rb
spec/commands/articles/create_article_spec.rb
spec/commands/articles/update_article_spec.rb
spec/factories/articles.rb
spec/models/article_spec.rb
spec/requests/api/v1/news/articles_spec.rb

- add language column to article
- eg: closes [#DAPP-735](https://ribon.atlassian.net/jira/software/c/projects/DAPP/boards/22?modal=detail&selectedIssue=DAPP-735)

feat: add language column to article

---

app/models/users/user_donation_stats.rb
spec/models/user_donation_stats_spec.rb

fix: remove function to donation first time on native

---

app/services/service/donations/balance_history.rb
spec/services/service/donations/balance_history_spec.rb

- the amount donated was supposed to be only free donations
- the amount_free_donations sql was wrong, it was not separating through cause
- Test A

Fix: Balance History amount donated

---

app/controllers/api/v1/non_profits_controller.rb
app/queries/non_profit_queries.rb
spec/requests/api/v1/non_profits_spec.rb

- Show only non profits active and with pool balance
- Test A

Tech 478: Show only non profits active and with pool balance

---

app/queries/non_profit_queries.rb

- it was not working properly without this part 
- Test A

fix: non profits index

---

app/controllers/api/v1/causes_controller.rb
app/queries/cause_queries.rb
app/workers/donations/update_pool_balance_worker.rb
spec/requests/api/v1/causes_spec.rb
spec/workers/donations/update_pool_balance_worker_spec.rb

- I did with non profits but forgot to do with causes 
- Test A

fix: only show causes with pool balance

---

app/workers/donations/update_pool_balance_worker.rb
spec/workers/donations/update_pool_balance_worker_spec.rb

- update pool balance only in production so we can test in dev and staging
- Test A

fix: update pool balance only in production

---

app/workers/donations/update_pool_balance_worker.rb
app/workers/mailers/send_one_week_inactivity_email_worker.rb
config/env.yml
spec/workers/donations/update_pool_balance_worker_spec.rb
spec/workers/mailers/send_one_week_inactivity_email_worker_spec.rb

- added another env var to check environment
- Test A

feat: added another env var to check environment

---

app/controllers/integrations/v1/vouchers_controller.rb
config/locales/en.yml
config/locales/pt-BR.yml
spec/requests/integrations/v1/vouchers_spec.rb

fix: update voucher error

---

app/commands/donations/donate.rb
app/controllers/api/v1/causes_controller.rb
app/controllers/api/v1/non_profits_controller.rb
app/jobs/donations/decrease_pool_balance_job.rb
app/jobs/donations/handle_post_donation_job.rb
app/models/pool_balance.rb
app/services/service/donations/pool_balances.rb
config/routes.rb
spec/commands/donations/donate_spec.rb
spec/factories/non_profit_impacts.rb
spec/jobs/donations/decrease_pool_balance_job_spec.rb
spec/jobs/donations/handle_post_donation_job_spec.rb
spec/requests/api/v1/causes_spec.rb
spec/requests/api/v1/non_profits_spec.rb
spec/requests/api/v1/vouchers/donations_spec.rb
spec/services/service/donations/pool_balances_spec.rb

- decrease pool balance with free donations
- don't let donate without pool balance
- a new route for list available causes and non profits based on pool balance
- Create a pool balance, then make a donation and see the balance decrease

Tech 479: decrease pool balance with free donations

---

app/services/service/contributions/contribution_fee_service.rb
config/environments/production.rb

- Fix production to load labeling rules
- Fix not allow negative fee balance cents
- Test A

fix: update production.rb and contribution fee to not be negative

---

app/controllers/api/v1/integrations/impacts_controller.rb

- Add beggining of day to impacts controller filter
- Test A

fix: update start_date to use beggining_of_day

---

config/env.yml

- Add polygon_gas_fee_url to env vars
- Test A

fix: add env var to polygon_gas_fee_url

---

app/models/contributions/contribution.rb
app/models/people/person_payment.rb
app/models/users/user.rb
app/services/service/contributions/contribution_fee_service.rb
db/migrate/20230411124309_fix_crypto_value_cents_name.rb
db/schema.rb
spec/factories/users.rb
spec/models/person_payment_spec.rb
spec/models/rule_groups/choose_between_big_donors_and_promoters_spec.rb
spec/models/rule_groups/fetch_contributions_with_low_remaining_amount_spec.rb
spec/models/rule_groups/pick_contribution_based_on_money_spec.rb
spec/models/user_spec.rb
spec/services/service/contributions/contribution_fee_calculator_service_spec.rb
spec/services/service/contributions/contribution_fee_service_spec.rb

- Update crypto_value_cents variable name to usd_value_cents

fix: update crypto_value_cents variable name to usd_value_cents

---

app/commands/contributions/create_contribution.rb
app/models/contributions/contribution.rb
app/services/service/contributions/contribution_fee_service.rb
db/migrate/20230411135017_add_generated_fee_to_contributions.rb
db/schema.rb
spec/factories/contributions.rb
spec/models/contribution_spec.rb

- Add contribution generated_fee_cents

Add contribution generated_fee_cents

---

.rubocop.yml
app/commands/contributions/update_contribution_balance.rb
app/commands/donations/create_donations_batch.rb
app/models/contributions/contribution.rb
app/models/contributions/contribution_balance.rb
app/models/contributions/contribution_fee.rb
app/services/service/contributions/contribution_fee_service.rb
db/migrate/20230411182152_fix_total_fees_increased_cents_name.rb
db/migrate/20230411183002_add_payer_contribution_increased_amount_cents_to_contribution_fees.rb
db/schema.rb
spec/factories/contribution_balances.rb
spec/factories/contribution_fees.rb
spec/models/contribution_balance_spec.rb
spec/models/contribution_fee_spec.rb

- Update total_increased_amount to contribution_increased_amount

feat: update total_increased_amount to contribution_increased_amount

---

app/services/service/contributions/contribution_fee_calculator_service.rb
app/services/service/contributions/contribution_fee_service.rb
spec/services/service/contributions/contribution_fee_calculator_service_spec.rb

- Update logic to calculate proportional_fee

Update logic to calculate proportional_fee

---

app/services/service/contributions/contribution_fee_service.rb

- Update logic to calculate fee for the last contribution balance
- Test A

Update logic to calculate fee for the last contribution balance

---

app/commands/contributions/labeling/determine_chosen_contribution.rb
app/models/contributions/contribution_balance.rb
app/services/service/contributions/contribution_fee_calculator_service.rb
app/services/service/contributions/handle_remaining_contribution_fee.rb
app/services/service/contributions/ticket_labeling_service.rb
spec/models/contribution_balance_spec.rb
spec/services/service/contributions/contribution_fee_calculator_service_spec.rb

- Add interoperability between tickets and fees balance 
- Test A

refactor: add interoperability between tickets and fee balances

---

app/blueprints/person_payment_blueprint.rb
app/controllers/api/v1/person_payments_controller.rb
config/routes.rb

- This adds a route for showing individual big donor donations (so we can show them on manager big donations details page)
- [#tech-470](https://ribon.atlassian.net/browse/TECH-470?atlOrigin=eyJpIjoiZjlkMmYwN2ZlN2NlNGE2N2JkYzI5ZDViM2ZiZTZhZmYiLCJwIjoiaiJ9)
- make a request for person_payments/big_donor_donation/[id] (for a big donor donation id)

feat: adds a big donor donation show route

---

app/blueprints/person_payment_blueprint.rb

- Adds a safe operator so we don't get the 500 error on big donors donations request anymore
- do a request for https://dapp-dev-api.ribon.io/api/v1/person_payments/big_donors

fix: fixes 500 error

---

app/controllers/api/v1/users_controller.rb

- Add voucher validation to useCanDonate
- Test A

fix: add can donate voucher validation

---

app/controllers/api/v1/legacy/legacy_user_impact_controller.rb
config/env.yml
spec/requests/api/v1/legacy/legacy_user_impact_controller_spec.rb

- added authorization token to legacy route
- update env var
- Test A

fix: added authorization token to legacy route

---

app/blueprints/legacy_non_profit_blueprint.rb
app/commands/legacy/create_legacy_user_impact.rb
app/models/legacy/legacy_non_profit.rb
db/migrate/20230426173202_add_impact_cost_ribons_to_legacy_non_profit.rb
db/schema.rb
spec/commands/legacy/create_legacy_user_impact_spec.rb
spec/factories/legacy/legacy_non_profits.rb
spec/jobs/legacy/create_legacy_user_impact_job_spec.rb
spec/models/legacy/legacy_non_profit_spec.rb

- Added more info for impact migration
- Test A

fix/TECH 511: more info

---

app/controllers/api/v1/users_controller.rb
app/models/users/user.rb
db/schema.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/requests/api/v1/users_spec.rb

- Add donate app to user can donate
- eg: closes [#DAPP-718]()

[DAPP-718] Add donate app 

---

app/models/people/person_blockchain_transaction.rb
app/services/service/donations/pool_balances.rb
spec/models/person_blockchain_transaction_spec.rb
spec/services/service/donations/pool_balances_spec.rb

- increase pool balance when the money is added to the contract
- Test A

tech 507: increase pool balance

---

app/queries/contribution_queries.rb
spec/queries/contribution_queries_spec.rb
spec/services/service/contributions/fees_labeling_service_spec.rb

- Update ContributionFeeableQuery to get contributions with the same receiver
The fees are only paid by contributions to the same pool, eg., the same receiver
- Test A

fix: add receiver to ContributionFeeableQuery

---

app/models/legacy/legacy_user_impact.rb
db/migrate/20230427184140_change_total_donated_usd_on_legacy_user_impact.rb
db/schema.rb
spec/factories/legacy/legacy_user_impacts.rb
spec/models/legacy/legacy_user_impact_spec.rb

- change column total_donated_usd to decimal
- Test A

fix: change column total_donated_usd to decimal

---

app/models/users/user.rb
config/initializers/rails_admin.rb
db/migrate/20230427153720_add_deleted_at_to_users.rb
db/schema.rb
spec/factories/users.rb
spec/models/user_spec.rb

- Adds a temporary solution for "deleting" users so we don't lose the records
- run `rails db:migrate`
- [#tech-527](https://ribon.atlassian.net/browse/TECH-527?atlOrigin=eyJpIjoiMWUxZWQ1OTk4YzQ1NDQ5Yzg5NmUxNTQzMTI3OGM5YTQiLCJwIjoiaiJ9)
- Open rails admin and try to edit a user

feat: adds deleted at field to user

---

app/lib/web3/contracts/ribon_contract.rb

- Update gas limit to create pool
- Test A

chore: add 500_000 of gas limit to create pool

---

app/commands/legacy/create_legacy_user_impact.rb

- update_current_id was wrong
- Test A

fix: update current_id

---

app/commands/contributions/create_non_feeable_contribution.rb
app/commands/manager/payments/cryptocurrency.rb
app/controllers/api/v1/manager/payments/cryptocurrency_controller.rb
lib/ext/string.rb
spec/commands/manager/payments/cryptocurrency_spec.rb
spec/requests/api/v1/manager/payments/cryptocurrency_controller_spec.rb

- Update non feeable contribution to create a Contribution with generated_fee_cents zero
- Test A

feat: add feeable to cryptocurrency

---

app/services/service/contributions/remaining_contribution_fee_handler_service.rb

- Add ticket balance transfer to fees balance
- Test A

fix: add ticket balance transfer to fees balance

---

app/models/legacy/legacy_non_profit.rb
spec/models/legacy/legacy_non_profit_spec.rb

- Remove logo url validation of LegacyNonProfit
we don't need this since we can attach a logo to it
- Test A

fix: remove logo_url validation in LegacyNonProfit

---

app/controllers/api/v1/users_controller.rb

- Fix can donate route
- Test A

fix: update can_donate route with voucher check

---

app/blueprints/legacy_contributions_blueprint.rb
spec/requests/api/v1/users/legacy_impacts_spec.rb

- Add ID to legacy contribution blueprint
- Test A

chore: add id to LegacyContributionsBlueprint

---

app/services/service/contributions/remaining_contribution_fee_handler_service.rb

- Fix circular call of labeling services
- Test A

fix: remove circular call of ticket labeling services

---

app/commands/legacy/create_legacy_user_impact.rb
spec/commands/legacy/create_legacy_user_impact_spec.rb

- added impact en and pt_br 
- Test A

Tech 531: receive impact en and pt_br from web2

---

app/models/legacy/legacy_contribution.rb
spec/models/legacy/legacy_contribution_spec.rb

- Remove validation of legacy payment method
Not all contributions in web2 had payment method set. We can investigate later which method was used, but for now this will not be used at all, so it doesnt need to be mandatory.
- Test A

fix: remove validation of legacy payment method

---

config/initializers/rails_admin.rb

- Add legacy integration to rails admin
- Test A

feat: add LegacyIntegration to rails admin

---

app/commands/legacy/create_legacy_integration_impact.rb

- Add reference date to query for previous created legacy integration impact
- Test A

fix: add reference_date query to CreateLegacyIntegrationImpact

---

app/models/legacy/legacy_non_profit.rb
spec/models/legacy/legacy_non_profit_spec.rb

- Remove impact description validation
This is not needed since we are using mobility to populate this field
- Test A

fix: remove impact description validation

---

app/blueprints/user_completed_task_blueprint.rb
app/commands/users/upsert_task.rb
app/models/users/user_completed_task.rb
spec/commands/users/upsert_task_spec.rb
spec/requests/api/v1/users_spec.rb

We are moving some virtual fields to the backend in order to simplify our task context, that depends on the backend, a current state and a tasks object.

refactor: completed task virtual fields

---

app/controllers/managers/v1/causes_controller.rb
app/controllers/managers/v1/non_profits_controller.rb
app/controllers/managers/v1/stories_controller.rb
spec/requests/managers/v1/non_profits_spec.rb

add the new NGO params to the managers endpoint
- Test A

fix: ngo params in the manager controller

---

app/models/non_profits/non_profit.rb
config/routes.rb

fix some mobility params in the nonprofit model
- Test A

fix: mobility attributes params

---

app/controllers/api/v1/users_controller.rb
app/models/users/user.rb
app/models/users/user_donation_stats.rb
config/routes.rb
spec/queries/user_queries_spec.rb

- we need to know if the user has accessed ribon with this integration before 

feat: adds first_access_to_integration route

---

app/lib/web3/utils/gas.rb
spec/lib/web3/utils/gas_spec.rb

- increased max fee for 50k donation
- Just to see if this way the transaction will succeed
- Test A

fix: increase max fee for 50k donation

---

app/blueprints/contribution_stats_blueprint.rb
app/services/service/contributions/statistics_service.rb
spec/blueprints/contribution_stats_blueprint_spec.rb
spec/services/service/contributions/statistics_service_spec.rb

- added usage percentage
- Test A

Tech 536: gift status

---

app/jobs/legacy/create_legacy_contributions_job.rb
app/jobs/legacy/create_legacy_integration_impact_job.rb
app/jobs/legacy/create_legacy_user_impact_job.rb
app/services/service/contributions/ticket_labeling_service.rb
config/sidekiq.yml

- Add validation to check if payer contribution was found in labeling
- Test A

fix: add validation to check if payer contribution was found in labeling

---

app/commands/legacy/create_legacy_contribution.rb
app/commands/legacy/create_legacy_integration_impact.rb
spec/commands/legacy/create_legacy_contribution_spec.rb
spec/factories/legacy/legacy_contributions.rb

- Add validation to check if legacy contribution exists
- Test A

fix: add validation to check if legacy contribution exists

---

app/services/service/contributions/direct_impact_service.rb
spec/services/service/contributions/direct_impact_service_spec.rb

- Fix value passed in direct impact service to non profit impact calculator
- Test A

fix: update value in direct_impact_service

---

app/controllers/api/v1/users/legacy_impacts_controller.rb

- legacy contributions order by day desc
- Test A

fix: legacy contributions order by day desc

---

app/blueprints/user_statistics_blueprint.rb
app/services/service/users/statistics.rb
spec/commands/users/calculate_statistics_spec.rb
spec/requests/api/v1/users/statistics_spec.rb

- add last donated non profit to user statistics
- eg: closes [#DAPP-869]()

feat: add last donated non profit to user statistics

---

config/initializers/rails_admin.rb

- add user_tasks_statistics to admin
- Test A

fix: add user_tasks_statistics to admin

---

app/controllers/api/v1/payments/credit_cards_controller.rb
app/controllers/api/v1/payments/cryptocurrency_controller.rb

- On the wedding page the user is created with language en and after send the contribution, the email is updated with the right language, so now we are passing the language on creation
- Test A

fix: user language

---

app/commands/donations/blockchain_transactions/update_failed_transactions.rb
app/commands/person_payments/blockchain_transactions/update_failed_transactions.rb
app/lib/web3/contracts/ribon_contract.rb
app/models/blockchain_transaction.rb
app/models/people/person_blockchain_transaction.rb
spec/commands/donations/blockchain_transactions/update_failed_transactions_spec.rb
spec/commands/person_payments/blockchain_transactions/update_failed_transactions_spec.rb
spec/lib/web3/contracts/ribon_contract_spec.rb
spec/models/blockchain_transaction_spec.rb
spec/models/person_blockchain_transaction_spec.rb

- fix on contribute to non profit to add the token approval
- new status to blockchain transactions
- Test A

Tech 604: fix blockchain transactions processing

---

app/blueprints/cause_blueprint.rb
app/blueprints/non_profit_blueprint.rb
app/controllers/api/v1/causes_controller.rb
spec/requests/api/v1/causes_spec.rb

- Remove non profits from minimal view of cause
We are rendering the non profits in a semi-loop in the free_non_profits request, making it slower
- Test A

refactor: update minimal view of causes blueprint

---

app/controllers/patrons/v1/contributions_controller.rb

- Order patron contributions by created at
- Test A

feat: update patron contributions route to return by created at desc

---

app/controllers/webhooks/alchemy_controller.rb
config/env.yml
config/environments/development.rb
config/routes.rb
spec/requests/webhooks/alchemy_controller_spec.rb
spec/support/webhooks/alchemy/dropped.json

- Alchemy webhook to update dropped transactions
- update an environment variable
- Test A

feat: alchemy webhook

---

app/commands/donations/create_batch_blockchain_donation.rb
app/commands/givings/community_treasure/add_balance.rb
app/commands/givings/non_profit_treasure/add_balance.rb
app/jobs/person_payments/retry_blockchain_transactions_job.rb
spec/commands/givings/community_treasure/add_balance_spec.rb
spec/commands/givings/non_profit_treasure/add_balance_spec.rb

- Added sleep on add balance
- Test A

Tech 614: Added sleep on add balance

---

app/queries/donation_queries.rb

- Added the new status from blockchain transaction
- Test A

fix: amount with batch failed including new status

---

app/jobs/givings/payment/add_giving_cause_to_blockchain_job.rb
app/jobs/givings/payment/add_giving_non_profit_to_blockchain_job.rb

- change queue because of sleep
- Test A

fix: queue

---

app/services/service/contributions/statistics_service.rb

- Round statistics service money formats
- Test A

fix: update format_money method on contributions statistics service

---

app/services/service/donations/statistics.rb
spec/services/service/donations/statistics_spec.rb

- Add formatted impact to impact service
This will be helpful for integrations to use our impact normalized (such as DNN)
- Test A

feat: add formatted_impact to impact per non profit

---

app/blueprints/integration_impact_blueprint.rb

- Add formatted impact to blueprint
- Test A

chore: ad formatted_impact to integration impact blueprint

---

app/blueprints/contribution_blueprint.rb
app/models/causes/cause.rb
app/models/non_profits/non_profit.rb
spec/requests/api/v1/users/contributions_spec.rb
spec/requests/patrons/v1/contributions_spec.rb

Add cause on stats blueprint

---

app/blueprints/contribution_blueprint.rb
spec/requests/api/v1/users/contributions_spec.rb

Add receiver in all contributions blueprint

Add receiver in all contributions blueprint

---

app/services/service/givings/payment/gateway_factory.rb

Change capitalize to camelcase

fix: camelcase

---

app/models/people/person_payment.rb
app/services/service/contributions/statistics_service.rb
spec/blueprints/contribution_stats_blueprint_spec.rb
spec/lib/currency/converters_spec.rb
spec/lib/currency/rates_spec.rb
spec/requests/api/v1/users/contributions_spec.rb
spec/services/service/contributions/statistics_service_spec.rb
spec/support/vcr_cassettes/conversion_multiple_rates.yml
spec/support/vcr_cassettes/conversion_rate_usd_brl.yml

- Fix currency in labeling for user
- Test A

refactor: update all tests to use downcased currencies

---

app/blueprints/offer_blueprint.rb
spec/blueprints/offer_blueprint_spec.rb
spec/requests/api/v1/givings/offers_spec.rb

Show offer gateway on minimal view

HOTFIX: show gateway on blueprint

---

app/controllers/api/v1/givings/fees_controller.rb
app/models/people/person_payment.rb
spec/requests/api/v1/givings/fees_spec.rb

Fix gateway name from string to symbol

fix: convert gateway to symbol

---

app/services/user_services/user_impact.rb

- Add guard clause to user impact

fix: add guard clause to impact sum by non profit in user impact

---

app/controllers/managers/managers_controller.rb

- add set language to manager controller
- Test A

fix: i18n on manager controller

---

app/lib/impact/normalizer.rb

- To fix this bug on dapp-dev-api
- Test A

fix: when impact description is null

---

app/controllers/api/v1/causes_controller.rb
app/controllers/managers/v1/causes_controller.rb
app/models/causes/cause.rb
db/migrate/20230623142540_add_active_to_causes.rb
db/schema.rb
spec/factories/causes.rb
spec/factories/non_profits.rb
spec/models/cause_spec.rb

-  add active on cause and inactive non profits when cause is inactive

feat: add active on cause and inactive non profits when cause is inactive

---

app/controllers/api/v1/users/devices_controller.rb
app/models/device.rb
app/models/users/user.rb
config/routes.rb
db/migrate/20230726192241_create_devices.rb
db/schema.rb
spec/factories/user/devices.rb
spec/models/user/device_spec.rb
spec/requests/api/v1/users/devices_spec.rb

- Add devices table to get device id and device token to send notification

Add devices table

---

app/queries/user_queries.rb

- Update labelable contributions order
- Test A

chore: update labelable contributions to order by created_at desc

---

app/models/people/person_payment.rb
spec/models/person_payment_spec.rb

fix: remove fees for crypto payments

---

app/controllers/api/v1/payments/stores_controller.rb
app/lib/payment/gateways/stripe/payment_processor.rb
app/lib/payment/gateways/stripe_global/payment_processor.rb

- Add response to stores controller
- Test A

feat: add stores controller response

---

app/models/people/person_payment.rb
app/models/subscription.rb
app/observers/person_payment_observer.rb
db/migrate/20230801172348_add_subscription_to_person_payments.rb
db/schema.rb
spec/factories/subscriptions.rb
spec/models/person_payment_spec.rb
spec/models/subscription_spec.rb
spec/observers/person_payment_observer_spec.rb

- Adjust the person payments table including a relation with the subscribers.
- Test A

Feat: adjust person_payments table

---

app/jobs/contributions/handle_patron_contribution_email_job.rb

- don't try to send email if percentage is minor then 5
- Test A

fix: don't try to send email if percentage is minor then 5

---

app/queries/contribution_queries.rb

- separate by receiver
- Test A

fix: separate by receiver

---

app/services/service/contributions/direct_impact_service.rb
spec/requests/patrons/v1/contributions/impacts_spec.rb
spec/services/service/contributions/direct_impact_service_spec.rb

- when the donation is in brl it was showing the total amount in usd
- Test A

Fix: direct impact service currency

---

app/controllers/api/v1/news/articles_controller.rb
app/models/article.rb
app/models/legacy/legacy_user_impact.rb
db/schema.rb
spec/factories/articles.rb
spec/models/article_spec.rb
spec/requests/api/v1/news/articles_spec.rb

- get articles with the correct language
- Test A

fix: article language

---

app/jobs/mailers/contributions/send_patron_contributions_100_percent_email_job.rb
app/jobs/mailers/contributions/send_patron_contributions_10_percent_email_job.rb
app/jobs/mailers/contributions/send_patron_contributions_25_percent_email_job.rb
app/jobs/mailers/contributions/send_patron_contributions_50_percent_email_job.rb
app/jobs/mailers/contributions/send_patron_contributions_5_percent_email_job.rb
app/jobs/mailers/contributions/send_patron_contributions_75_percent_email_job.rb
app/jobs/mailers/contributions/send_patron_contributions_95_percent_email_job.rb
app/services/service/contributions/statistics_service.rb
spec/jobs/mailers/contributions/send_patron_contributions100_percent_email_job_spec.rb
spec/jobs/mailers/contributions/send_patron_contributions10_percent_email_job_spec.rb
spec/jobs/mailers/contributions/send_patron_contributions25_percent_email_job_spec.rb
spec/jobs/mailers/contributions/send_patron_contributions50_percent_email_job_spec.rb
spec/jobs/mailers/contributions/send_patron_contributions5_percent_email_job_spec.rb
spec/jobs/mailers/contributions/send_patron_contributions75_percent_email_job_spec.rb
spec/jobs/mailers/contributions/send_patron_contributions95_percent_email_job_spec.rb

- fix receiver name language
- Test A

fix: patron receiver name language

---

app/blueprints/cause_blueprint.rb
app/blueprints/pool_blueprint.rb
app/controllers/api/v1/causes_controller.rb
app/controllers/api/v1/manager/pools_controller.rb
app/controllers/api/v1/non_profits_controller.rb
app/controllers/managers/v1/pools_controller.rb
app/models/causes/cause.rb
app/models/users/user.rb
db/schema.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/requests/api/v1/causes_spec.rb
spec/requests/api/v1/non_profits_spec.rb
spec/requests/managers/v1/causes_spec.rb

- randomize the array of causes
- eg: closes [#PROD-73]()

feat: add shuffle to randomize the array of causes

---

app/controllers/webhooks/stripe_controller.rb

- Use stripe global endpoint secret for now.
- Test A

fix: use stripe global endpoint secret

---

app/commands/givings/payment/create_order.rb
app/commands/givings/payment/order_types/credit_card.rb
app/commands/givings/payment/order_types/store_pay.rb
app/models/subscription.rb
config/initializers/rails_admin.rb
db/migrate/20230809124908_change_offer_type_on_subscription.rb
db/migrate/20230809172133_change_status_type_on_subscription.rb
db/migrate/20230810145122_add_integration_to_subscription.rb
db/schema.rb
spec/commands/givings/payment/create_order_spec.rb
spec/factories/subscriptions.rb
spec/models/subscription_spec.rb

- Create a subscription when credit card or store pay operation is `subscribe`. 
- Test A

Feat: create subscription

---

app/blueprints/legacy_non_profit_blueprint.rb

- fixes legacy non proit loggo field

fix: fixes logo field on non-profit-logo

---

app/controllers/webhooks/stripe_global_controller.rb
config/routes.rb
spec/requests/webhooks/stripe_global_controller_spec.rb

- Add stripe global controller
After this is in production, change the endpoint of stripe global webhooks in stripe's dashboard
- Test A

fix: add stripe global webhook controller

---

app/controllers/webhooks/stripe_controller.rb

- Update stripe controller endpoint secret
- [] Chore (change that does not effect how the code works, eg: change color)
- Test A

feat: update stripe controller endpoint secret

---

app/models/subscription.rb
db/migrate/20230815145740_change_receiver_type_on_subscription.rb
db/schema.rb
spec/factories/subscriptions.rb
spec/models/subscription_spec.rb

- change receiver type on subscription
- Test A

fix: change receiver type on subscription

---

app/models/causes/cause.rb
app/models/non_profits/non_profit.rb
app/models/people/customers/customer.rb
db/migrate/20230815192623_change_status_on_subscription.rb
db/migrate/20230815192726_change_offer_on_subscription.rb
db/schema.rb
spec/models/cause_spec.rb
spec/models/customer_spec.rb
spec/models/non_profit_spec.rb

- Added has many subscriptions on nonprofits, causes and customers
- removed column status and offer to add again
- Test A

Fix: subscription receiver

---

app/commands/givings/payment/cancel_subscription.rb
app/commands/givings/payment/credit_card_refund.rb
app/controllers/api/v1/payments/subscriptions_controller.rb
app/lib/payment/gateways/stripe/billing/subscription.rb
app/lib/payment/gateways/stripe_global/billing/subscription.rb
config/routes.rb
spec/commands/givings/payment/cancel_subscription_spec.rb
spec/commands/givings/payment/credit_card_refund_spec.rb
spec/factories/payment/offers.rb
spec/lib/payment/gateways/stripe/billing/subscription_spec.rb
spec/lib/payment/gateways/stripe/payment_processor_spec.rb
spec/lib/payment/gateways/stripe_global/billing/subscription_spec.rb
spec/lib/payment/gateways/stripe_global/payment_processor_spec.rb
spec/requests/api/v1/payments/subscriptions_spec.rb
spec/support/vcr_cassettes/stripe_payment_method.yml

- Cancel subscription command
- obs.: update `Subscription.delete` to `Subscription.cancel` because `delete` is deprecated
- Test A

Feat: cancel subscription

---

app/workers/donations/send_donation_batch_worker.rb

- donations from july 31 did not have a batch yet because of this bug
- Test A

fix: batches period

---

app/services/service/contributions/contribution_fee_delete_service.rb
app/services/service/contributions/donation_contribution_delete_service.rb
spec/services/service/contributions/contribution_fee_delete_service_spec.rb
spec/services/service/contributions/donation_contribution_delete_service_spec.rb

- Add donation_contribution_delete_service
- Refactor contribution_fee_delete_service to use active record transaction and update its test
- Test A

feat: add donation_contribution_delete_service

---

app/models/people/person_blockchain_transaction.rb
spec/models/person_blockchain_transaction_spec.rb

- Remove treasure entry status check to label
- Test A

fix: remove treasury entry status check

---

app/jobs/events/contributions/send_contribution_event_job.rb
spec/jobs/events/contributions/send_contribution_event_job_spec.rb

- Adds subscribed event in order to send recurrence emails 
- update customerio local envs variables
- closes [PROD3-95](https://ribon.atlassian.net/browse/PROD3-95)
- closes [PROD3-96](https://ribon.atlassian.net/browse/PROD3-96)
- Test A

feat: adds subscribed event

---

app/models/people/person_blockchain_transaction.rb

- Fixes blockchain success trigger
This was not being triggered
- Test A

fix: update handle blockchain success trigger

---

app/commands/givings/payment/create_order.rb
app/commands/tracking/add_utm.rb
spec/commands/givings/payment/create_order_spec.rb
spec/models/contribution_spec.rb

- Now create order return person payment

Return person payment on payments controllers

---

spec/models/contribution_spec.rb

- I got an error because of that, the ids order was different
- Test A

fix: tests

---

app/commands/givings/payment/create_order.rb
app/controllers/api/v1/payments/credit_cards_controller.rb
app/controllers/api/v1/payments/cryptocurrency_controller.rb
app/controllers/api/v1/payments/pix_controller.rb
app/controllers/api/v1/payments/stores_controller.rb
spec/commands/givings/payment/create_order_spec.rb
spec/requests/api/v1/payments/credit_cards_spec.rb
spec/requests/api/v1/payments/cryptocurrencies_spec.rb
spec/requests/api/v1/payments/pix_spec.rb
spec/requests/api/v1/payments/stores_spec.rb
spec/requests/managers/v1/payments/credit_cards_spec.rb

- Fix create order return
- Test A

fix: update create order to return necessary keys

---

app/lib/impact/normalizer.rb

- Update MAX_DAYS_PER_DONOR_RECIPIENT
This new number will allow the convertions between days to years / months / days to have a higher margin to avoid wrong convertions
- Test A

fix: update MAX_DAYS_PER_DONOR_RECIPIENT to 733

---

app/controllers/api/v1/users/subscriptions_controller.rb

fix: current_user nil

---

app/controllers/api/v1/payments/credit_cards_controller.rb
app/controllers/api/v1/payments/cryptocurrency_controller.rb
app/controllers/api/v1/payments/stores_controller.rb
spec/requests/api/v1/payments/credit_cards_spec.rb
spec/requests/api/v1/payments/stores_spec.rb

- If language changed the user would not be created
- Test A

Fix: Find or create user

---

app/lib/currency/rates.rb
config/env.yml

- Add currency convertion api backup
- Test A

feat: add backup url to get currency convertion

---

.github/workflows/test-deploy.yml
app/commands/donations/donate.rb
app/models/people/person_blockchain_transaction.rb
app/services/labeling/relabel_service.rb
app/workers/contributions/relabel_worker.rb
config/initializers/rails_admin.rb
config/schedule.yml
config/sidekiq.yml
spec/commands/donations/donate_spec.rb
spec/factories/contributions.rb
spec/models/person_blockchain_transaction_spec.rb
spec/services/labeling/relabel_service_spec.rb
spec/workers/contributions/relabel_worker_spec.rb

- Add relabel service
- Test A

feat: add relabel service

---

app/commands/users/anonymize.rb

- added deleted at on delete user
- Test A

fix: delete user

---

spec/commands/givings/payment/create_order_spec.rb

- Add tests to create order result
- Test A

test: add create order result test

---

app/controllers/api/v1/donations_controller.rb

- Allow donation by integration uuid
- Donation on app pass the integration uuid
- Donation on app with integration

fix: donation by integration uuid

---

app/controllers/api/v1/vouchers/donations_controller.rb

- allow donation with integration uuid
- Test A

fix: donation by integration uuid with voucher

---

app/blueprints/integration_blueprint.rb
app/controllers/managers/v1/integrations_controller.rb
app/models/integrations/integration.rb
config/env.yml
spec/blueprints/integration_blueprint_spec.rb
spec/models/integration_spec.rb
spec/requests/managers/v1/integrations_spec.rb

- added  integration deeplink address to show on manager
- Test A

feat: integration deeplink address

---

app/controllers/api/v1/users/impacts_controller.rb
config/routes.rb
spec/requests/api/v1/users/impacts_spec.rb

- route for count user donations on app
- Test A

feat: route for count user donations on app

---

app/lib/payment/gateways/stripe/events/invoice_paid.rb
app/lib/payment/gateways/stripe/events/invoice_payment_failed.rb
app/lib/payment/gateways/stripe_global/events/invoice_paid.rb
app/lib/payment/gateways/stripe_global/events/invoice_payment_failed.rb
spec/lib/payment/gateways/stripe/events/invoice_paid_spec.rb
spec/lib/payment/gateways/stripe/events/invoice_payment_failed_spec.rb

- save external id on invoice events
- Test A

fix: save external id on invoice events

---

app/commands/person_payments/blockchain_transactions/cause/update_api_only_transactions.rb
app/commands/person_payments/blockchain_transactions/cause/update_failed_transactions.rb
app/commands/person_payments/blockchain_transactions/non_profit/update_failed_transactions.rb
spec/commands/person_payments/blockchain_transactions/cause/update_api_only_transactions_spec.rb
spec/commands/person_payments/blockchain_transactions/cause/update_failed_transactions_spec.rb
spec/commands/person_payments/blockchain_transactions/non_profit/update_failed_transactions_spec.rb

- retry person payments blockchain transactions with new payment methods
- Test A

fix: retry person payments blockchain transactions with new payment methods

---

app/commands/givings/payment/create_order.rb
app/lib/payment/gateways/stripe/events/invoice_paid.rb
app/lib/payment/gateways/stripe/payment_processor.rb
app/lib/payment/gateways/stripe_global/events/invoice_paid.rb
app/lib/payment/gateways/stripe_global/payment_processor.rb
spec/commands/givings/payment/create_order_spec.rb
spec/factories/payment/credit_cards.rb
spec/factories/payment/offer_gateways.rb
spec/factories/payment/offers.rb
spec/lib/payment/gateways/stripe/events/invoice_paid_spec.rb
spec/support/vcr_cassettes/stripe_payment_method.yml
spec/support/vcr_cassettes/stripe_payment_method_blocked.yml
spec/support/vcr_cassettes/stripe_payment_method_error.yml
spec/support/vcr_cassettes/stripe_payment_method_pending.yml

- set subscription inactive when payment failed
- set subscription active when payment succeeded
- Test subscription with a card that requires action
- Test subscription with a blocked card
- Test subscription and unique with a valid card

prod-215: set subscription inactive when payment failed

---

app/commands/givings/payment/order_types/store_pay.rb

- Added platform on subscription when store pay
- Test A

fix: platform on subscription

---

app/models/subscription.rb
app/models/users/user_config.rb
db/migrate/20231003163930_create_user_configs.rb
db/schema.rb
spec/factories/subscriptions.rb
spec/factories/user_configs.rb
spec/models/subscription_spec.rb
spec/models/user_config_spec.rb

- Add UserConfig model
- Add logic to set if user allowed email marketing
- Test A

feat: add UserConfig model

---

app/jobs/mailers/contributions/send_patron_contributions_10_percent_email_job.rb
app/services/service/contributions/statistics_service.rb
spec/jobs/mailers/contributions/send_patron_contributions10_percent_email_job_spec.rb

- the email was showing the impact in portuguese, 
so I transfered some data to the email job, where the language is set
- Test A

fix: impact language on patron email

---

app/controllers/managers/v1/causes_controller.rb

- Add status as cause params to manager

fix: adds status as causes params

---

app/commands/donations/donate.rb
app/models/people/person_blockchain_transaction.rb
config/schedule.yml
spec/commands/donations/donate_spec.rb
spec/models/person_blockchain_transaction_spec.rb

Feat: temporary disable labeling

---

app/commands/donations/donate.rb
app/models/people/person_blockchain_transaction.rb
app/services/service/contributions/fees_labeling_service.rb
app/services/service/contributions/ticket_labeling_service.rb

- Fix relabel service disable clauses
- Test A

fix: update disable labeling clauses

---

app/jobs/givings/payment/add_giving_cause_to_blockchain_job.rb
app/jobs/givings/payment/add_giving_non_profit_to_blockchain_job.rb

- just to see if it solves the hash duplication problem
- Test A

fix: remove sidekiq retry

---

app/blueprints/impression_card_blueprint.rb
app/controllers/managers/v1/impression_cards_controller.rb
app/models/impression_card.rb
db/migrate/20231023144113_add_active_and_client_to_impression_card.rb
db/schema.rb
spec/factories/impression_cards.rb
spec/models/impression_card_spec.rb
spec/requests/managers/v1/impression_cards_spec.rb

chore: Add active and client fields to the ImpresionCard model

---

app/controllers/api/v1/impression_cards_controller.rb
config/routes.rb
spec/requests/api/v1/impression_cards_spec.rb

- Public route to fetch impression cards
- Test A

feat: impression cards public route

---

app/controllers/api/v1/impression_cards_controller.rb
app/models/impression_card.rb
spec/models/impression_card_spec.rb
spec/requests/api/v1/impression_cards_spec.rb

chore: validations for impression card

---

app/commands/givings/payment/credit_card_refund.rb
app/commands/givings/payment/find_payment_intent.rb
app/commands/givings/payment/generate_pix.rb
app/controllers/api/v1/payments/pix_controller.rb
app/lib/payment/gateways/stripe/entities/payment_intent.rb
app/lib/payment/gateways/stripe/payment_processor.rb
app/models/payment/payment_intent.rb
app/models/subscription.rb
config/routes.rb
db/schema.rb
spec/factories/subscriptions.rb
spec/lib/payment/gateways/stripe/payment_processor_spec.rb
spec/lib/payment/gateways/stripe_global/payment_processor_spec.rb
spec/models/subscription_spec.rb
spec/requests/api/v1/payments/pix_spec.rb
spec/support/vcr_cassettes/stripe_payment_method.yml

- Add routes to generate pix and find pix 
- eg: closes [#DAPP-240]()
- Test A

feat: add routes to generate and verify pix

---

Gemfile
Gemfile.lock
newrelic.yml

Add new relic gem and new relic yaml.
The license key should be on environment variables.

add: new relic

---

app/controllers/users/v1/donations_controller.rb
app/controllers/users/v1/vouchers/donations_controller.rb
config/routes.rb
db/schema.rb
spec/models/impression_card_spec.rb
spec/requests/users/v1/donations_spec.rb
spec/requests/users/v1/vouchers/donations_spec.rb

- donations routes for logged in users
- Test A

feat: donations routes for logged in users

---

app/controllers/users/v1/donations_controller.rb
config/routes.rb
spec/requests/users/v1/donations_spec.rb

- can donate for logged in users
- Test A

feat: users v1 can donate

---

app/commands/auth/accounts/set_account_tokens.rb
app/controllers/users/v1/authentication_controller.rb
spec/commands/auth/accounts/set_account_tokens_spec.rb

- return user on authenticate methods
- Test A

Prod 7: return user on authenticate methods

---

app/observers/person_payment_observer.rb
spec/models/impression_card_spec.rb
spec/observers/person_payment_observer_spec.rb

- send email to all payment methods except crypto
- Test A

Fix: send email to all payment methods except crypto

---

app/commands/users/anonymize.rb
app/models/subscription.rb
app/models/users/user.rb
app/models/users/user_profile.rb
config/initializers/rails_admin.rb
db/migrate/20231122122853_create_user_profiles.rb
db/schema.rb
spec/commands/users/anonymize_spec.rb
spec/factories/subscriptions.rb
spec/factories/user_profiles.rb
spec/models/subscription_spec.rb
spec/models/user_profile_spec.rb
spec/models/user_spec.rb

- New table UserProfile
- Test A

Prod2-255: table UserProfile

---

app/controllers/users/v1/configs_controller.rb
config/routes.rb

- adds get userconfigs route
- [X ] New feature (non-breaking change which adds functionality)

feat: adds get userconfigs route

---

app/commands/auth/accounts/set_account_tokens.rb
app/commands/users/create_profile.rb
spec/commands/users/create_profile_spec.rb
spec/factories/user/user_profiles.rb

- Update user profile name and photo with google
- Apple does not provide us with this information
- Test A

Prod3-255: Update user profile name and photo

---

app/blueprints/user_profile_blueprint.rb
app/controllers/users/v1/profile_controller.rb
app/models/article.rb
app/models/legacy/legacy_user_impact.rb
app/models/users/user.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/routes.rb
db/schema.rb
spec/factories/articles.rb
spec/factories/devices.rb
spec/models/article_spec.rb
spec/models/device_spec.rb
spec/requests/users/v1/profile_spec.rb

- User profile controller and tests
- eg: closes [#PROD3-256]()

[PROD3-256] User profile

---

app/commands/auth/accounts/send_authentication_email.rb
app/controllers/users/v1/authentication_controller.rb
spec/commands/auth/accounts/send_authentication_email_spec.rb
spec/requests/users/v1/authentication_spec.rb

- we are checking by integration because we couldn't think another way to check that
- Test A

fix: check extra ticket by integration id

---

app/commands/auth/accounts/send_authentication_email.rb
app/controllers/users/v1/authentication_controller.rb
spec/requests/users/v1/authentication_spec.rb

- the way that params were passed was wrong
- Test A

fix: send authentication email params

---

app/commands/auth/accounts/send_authentication_email.rb
app/commands/users/create_profile.rb
app/controllers/users/v1/profile_controller.rb
spec/commands/auth/accounts/send_authentication_email_spec.rb
spec/commands/auth/accounts/set_account_tokens_spec.rb
spec/support/vcr_cassettes/google_api_url.yml

- magic link was not creating a profile
- the profile controller was returning 500
- if url was blank it was throwing an error
- Test A

fix: create profile

---

app/commands/auth/accounts/set_account_tokens.rb

- check is user email matches
- Test A

fix: check is user email matches

---

app/services/auth/email_link_service.rb
config/env.yml

- deeplink for magiclink on app
- Test A

feat: deeplink for magiclink on app

---

app/models/ticket.rb
app/models/user_integration_collected_ticket.rb
db/migrate/20240103163355_create_tickets.rb
db/migrate/20240103163630_create_user_integration_collected_tickets.rb
db/schema.rb
spec/factories/tickets.rb
spec/factories/user_integration_collected_tickets.rb
spec/models/ticket_spec.rb
spec/models/user_integration_collected_ticket_spec.rb

- ticket and user_integration_collected_tickets tables
- Test A

Prod 262: ticket and user_integration_collected_tickets tables

---

app/commands/tickets/clear_all_collected_by_integration.rb
app/commands/tickets/clear_collected_by_integration.rb
app/commands/tickets/collect_by_integration.rb
app/jobs/tickets/clear_all_collected_by_integration_job.rb
app/jobs/tickets/clear_collected_by_integration_job.rb
app/models/integrations/integration.rb
app/workers/tickets/clear_all_collected_by_integration_worker.rb
config/schedule.yml
config/sidekiq.yml
spec/commands/tickets/clear_all_collected_by_integration_spec.rb
spec/commands/tickets/clear_collected_by_integration_spec.rb
spec/commands/tickets/collect_by_integration_spec.rb
spec/jobs/tickets/clear_all_collected_by_integration_job_spec.rb
spec/jobs/tickets/clear_collected_by_integration_job_spec.rb
spec/workers/tickets/clear_all_collected_by_integration_worker_spec.rb

- clear tickets collected by integration
- use https://hoppscotch.io/ to create the user integration ticket and use https://dapp-dev-api.ribon.io/sidekiq to run the job
- Test with an integration that has ticket_availability_in_minutes equals to 1

feat: clear collected by integration

---

spec/commands/tickets/donate_spec.rb

- Adds test to check association between voucher and donations on donate command
- [#prod3-390](https://ribon.atlassian.net/browse/PROD3-390?atlOrigin=eyJpIjoiOTg4ZmVkMGYyNDYyNDgyNDhjOGZmNTg4ZDJiNzQxY2EiLCJwIjoiaiJ9)
- run bundle exec rspec

test: checks voucher donation association

---

app/models/payment/offer.rb
db/migrate/20240130182515_add_category_to_offer.rb
db/schema.rb
spec/factories/payment/offers.rb

- added category to offers
- Test A

feat: added category to offers

---

app/workers/contributions/label_worker.rb

- relabel worker to run from last donation labelled

relabel worker to run from last donation labelled

---

config/schedule.yml

fix: add relabel on sidekiq

---

app/blueprints/offer_blueprint.rb
app/controllers/api/v1/givings/offers_controller.rb
app/controllers/managers/v1/givings/offers_controller.rb
config/routes.rb
spec/requests/api/v1/givings/offers_spec.rb
spec/requests/managers/v1/givings/offers_spec.rb

- Allow to edit offer category on manager
- delete unused code from api/v1/givings/offer
- Test A

Prod 398: allow to edit offer category on manager

---

app/services/labeling/relabel_service.rb

- relabel service setup records
- Test A

fix: relabel service setup records

---

app/blueprints/offer_blueprint.rb
app/blueprints/plan_blueprint.rb
app/models/payment/offer.rb
app/models/plan.rb
db/migrate/20240201123453_create_plans.rb
db/schema.rb
spec/blueprints/offer_blueprint_spec.rb
spec/blueprints/plan_blueprint_spec.rb
spec/factories/plans.rb
spec/models/offer_spec.rb
spec/models/plan_spec.rb
spec/requests/users/v1/tickets/tickets_controller_spec.rb

prod 399: table plan

---

app/observers/contribution_balance_observer.rb

- disable patron emails
- Test A

fix: disable patron emails

---

app/models/donation_contribution.rb
app/services/labeling/relabel_service.rb
spec/services/labeling/relabel_service_spec.rb
spec/services/service/contributions/direct_impact_service_spec.rb
spec/services/service/contributions/statistics_service_spec.rb

- fix: donation contribution validation

fix: donation contribution validation

---

app/controllers/api/v1/tickets/tickets_controller.rb
config/routes.rb
spec/requests/api/v1/tickets/tickets_controller_spec.rb
spec/requests/users/v1/tickets/collect_controller_spec.rb

- tickets available on api v1
- Test A

feat: tickets available on api v1

---

app/commands/tickets/collect_and_donate_by_integration.rb
app/controllers/api/v1/donations_controller.rb
app/controllers/api/v1/givings/user_givings_controller.rb
app/controllers/api/v1/payments/credit_cards_controller.rb
app/controllers/api/v1/payments/cryptocurrency_controller.rb
app/controllers/api/v1/payments/pix_controller.rb
app/controllers/api/v1/payments/stores_controller.rb
app/controllers/api/v1/person_payments_controller.rb
app/controllers/api/v1/tickets/collect_and_donate_controller.rb
app/controllers/api/v1/tickets/collect_controller.rb
app/controllers/api/v1/users/configs_controller.rb
app/controllers/api/v1/users/contributions_controller.rb
app/controllers/api/v1/users/devices_controller.rb
app/controllers/api/v1/users/impacts_controller.rb
app/controllers/api/v1/users/legacy_impacts_controller.rb
app/controllers/api/v1/users/statistics_controller.rb
app/controllers/api/v1/users_controller.rb
app/controllers/api/v1/vouchers/donations_controller.rb
spec/requests/api/v1/tickets/collect_controller_spec.rb

- Makes api/v1 controllers access email and user by using current_user
- [#prod-428](https://ribon.atlassian.net/browse/PROD3-428?atlOrigin=eyJpIjoiNmFkNmZiZTQ4OGNlNGI4Y2FlOTI3ZGQ3ODEyYzk5MjciLCJwIjoiaiJ9)
- use hoppscotch

refactor: adds access email/user by current_user

---

app/blueprints/offer_blueprint.rb
app/controllers/managers/v1/givings/offers_controller.rb
app/models/payment/offer.rb

- Create and edit plans through offers on manager
- Test A

Prod3 399: Create Plan on manager

---

app/blueprints/ribon_config_blueprint.rb
app/controllers/managers/v1/configs/ribon_config_controller.rb
app/models/configs/ribon_config.rb
config/initializers/rails_admin.rb
db/migrate/20240208135645_add_ribon_club_fee_percentage_to_ribon_config.rb
db/schema.rb
spec/factories/ribon_configs.rb
spec/models/ribon_config_spec.rb
spec/requests/api/v1/ribon_config_spec.rb
spec/requests/managers/v1/ribon_config_spec.rb

- Adds ribon_club_fee_percentage column to RibonConfig table
- [#prod3-405](https://ribon.atlassian.net/browse/PROD3-405?atlOrigin=eyJpIjoiYTIxNDhmMjM5ZWRkNDBjMThlOTRkMGI0MTE2YmQ2ODAiLCJwIjoiaiJ9)

feat: add ribon_club_fee_percentage to ribonconfig

---

app/commands/tickets/can_collect_by_external_id.rb

- can collect by external id false when external_id is nil
- Test A

fix: can collect by external id when external_id is nil

---

app/commands/tickets/collect_by_external_ids.rb
spec/commands/tickets/collect_by_external_ids_spec.rb

- limit by 5 collect ticket by external id
- Test A

fix: limit by 5 collect ticket by external id

---

app/controllers/api/v1/givings/offers_controller.rb
spec/requests/api/v1/givings/offers_spec.rb

- adds category filter to offers route
- update shared

feat: prod3-397

---

app/controllers/api/v1/tickets/tickets_controller.rb
app/observers/ticket_observer.rb

- if it is not on cache get it from database
- Test A

fix: tickets available

---

app/commands/givings/payment/credit_card_refund.rb
app/lib/payment/gateways/stripe/events/charge_refunded.rb
app/lib/payment/gateways/stripe_global/events/charge_refunded.rb
db/schema.rb
spec/commands/givings/payment/credit_card_refund_spec.rb
spec/lib/payment/gateways/stripe/events/charge_refunded_spec.rb
spec/lib/payment/gateways/stripe_global/events/charge_refunded_spec.rb

- call CancelSubscription on refund methods, before update subscription with status canceled
- Test A

fix: call CancelSubscription

---

app/models/people/person_payment.rb
spec/models/person_payment_spec.rb

- remove ribon club fee from crypto_amount and usd_value_cents
- Test A

Prod 408: remove ribon club fee from crypto_amount and usd_value_cents

---

app/lib/payment/gateways/stripe/events/invoice_payment_failed.rb
app/lib/payment/gateways/stripe_global/events/invoice_payment_failed.rb

- amount paid can't be used
- Test A

fix: amount_cents on invoice payment failed

---

app/blueprints/offer_blueprint.rb
app/controllers/api/v1/givings/offers_controller.rb
spec/requests/api/v1/givings/offers_spec.rb

- renders offers with plan view
- Test A

feat: prod3-368

---

app/controllers/users/v1/subscriptions_controller.rb
config/routes.rb
spec/requests/users/v1/subscriptions_spec.rb

- Add a route to see if user is member or not

feat: add route to return is is member

---

app/commands/tickets/collect_by_club.rb
app/controllers/users/v1/tickets/collect_controller.rb
config/routes.rb
spec/commands/tickets/collect_by_club_spec.rb
spec/requests/users/v1/tickets/collect_controller_spec.rb

- adds collect by club route to collet daily and monthly tickets
- eg: closes [PROD3-420](https://ribon.atlassian.net/browse/PROD3-420)

feat: adds collect by club route

---

app/commands/tickets/generate_club_tickets.rb
app/jobs/tickets/generate_club_daily_tickets_job.rb
app/workers/tickets/generate_club_daily_tickets_worker.rb
config/schedule.yml
spec/commands/tickets/generate_club_tickets_spec.rb
spec/jobs/tickets/generate_club_daily_tickets_job_spec.rb
spec/workers/tickets/generate_club_daily_tickets_worker_spec.rb

- Job to create daily tickets from club 
- Worker with cron job
- Command to generate tickets

[PROD3-418] Job to create daily tickets from club 

---

app/controllers/users/v1/tickets/tickets_controller.rb
config/routes.rb
spec/requests/users/v1/tickets/tickets_controller_spec.rb

- Route to check daily and monthly tickets to collect
- eg: closes [#PROD3-364]()

[PROD3-364] Route to tickets to collect

---

app/controllers/users/v1/subscriptions_controller.rb
spec/requests/users/v1/subscriptions_spec.rb

- Change key name to is_member
- Test A

fix: change key name to is member

---

app/lib/currency/rates.rb
config/env.yml

- new backup currency api
- Test A

Fix: new backup currency api

---

app/commands/users/verify_club_membership.rb
app/controllers/api/v1/users/subscriptions_controller.rb
app/controllers/users/v1/subscriptions_controller.rb
config/routes.rb
spec/requests/api/v1/users/subscriptions_spec.rb
spec/requests/users/v1/subscriptions_spec.rb

- move is_member to api/v1
- Test A

feat: move is_member to api/v1

---

app/blueprints/offer_blueprint.rb
app/blueprints/subscription_blueprint.rb
config/initializers/rails_admin.rb
spec/requests/api/v1/givings/offers_spec.rb
spec/requests/managers/v1/givings/offers_spec.rb

- add plans view on subscription blueprint

feat: add plans view

---

app/commands/tickets/donate.rb
app/jobs/donations/handle_post_donation_job.rb

- the donation was create and then the process revert, thats why the job could not find the donation
- I set de retry to 3 times
- I removed methods that was not supposed to be inside transaction
- Test A

fix: retry 3 times

---

app/observers/person_payment_observer.rb

- pix status requires_confirmation -> paid
- Test A

fix: pix requires confirmation

---

app/commands/givings/payment/create_order.rb

- monthly tickets - update subscription before payment
- Test A

fix: monthly tickets - update subscription before payment

---

app/commands/tickets/donate.rb

- donate only collected tickets
- Test A

fix: donate only collected tickets

---

app/blueprints/offer_blueprint.rb
app/controllers/managers/v1/givings/offers_controller.rb
spec/requests/managers/v1/givings/offers_spec.rb

- added external id for manager view
- Test A

fix: upsert offer on manager

---

app/blueprints/non_profit_impacts_blueprint.rb
spec/blueprints/non_profit_impacts_blueprint_spec.rb
spec/requests/api/v1/users/contributions_spec.rb
spec/requests/patrons/v1/contributions/impacts_spec.rb
spec/requests/patrons/v1/contributions_spec.rb
spec/requests/users/v1/contributions_spec.rb

- Add minimum number of tickets on non profit impacts blueprint
-  [#489](https://ribon.atlassian.net/jira/software/c/projects/PROD3/boards/28/backlog?selectedIssue=PROD3-489)

feat: add minimum number of tickets to nonprofit impacts blueprint

---

app/models/people/person_payment.rb
app/observers/subscription_observer.rb

- substract ribon club fee from all club payments
- send email only to club subscriptions
- Test A

fix: ribon club fee and email

---

app/commands/givings/payment/create_order.rb

- subscription was becoming active before payment
- Test A

fix: subscription was becoming active before payment

---

app/commands/givings/payment/order_types/credit_card.rb
app/commands/givings/payment/order_types/pix.rb
app/commands/givings/payment/order_types/store_pay.rb
app/controllers/api/v1/givings/user_givings_controller.rb
app/models/causes/cause.rb
app/models/contributions/contribution.rb
app/queries/user_queries.rb

- causes active and person payment impact 
- Test A

fix: causes active and person payment impact

---

app/controllers/users/v1/integrations_controller.rb

Fix metadata field param
- Test A

fix: metadata field

---

app/models/coupon.rb
config/initializers/rails_admin.rb
db/migrate/20240411163944_create_coupons.rb
db/schema.rb

-Add table Coupons
- eg: closes [#PROD3-468]()
- Create a coupon on rails admin

feat: add coupons table

---

app/models/coupon.rb
app/models/user_coupon.rb
app/models/user_expired_coupon.rb
app/models/users/user.rb
db/migrate/20240411202528_create_user_coupons.rb
db/migrate/20240412142253_create_user_expired_coupons.rb
db/schema.rb
spec/factories/coupons.rb
spec/factories/user_coupons.rb
spec/factories/user_expired_coupons.rb
spec/models/coupon_spec.rb
spec/models/user/user_spec.rb
spec/models/user_coupon_spec.rb
spec/models/user_expired_coupon_spec.rb

- UserCoupon
- UserExpiredCoupon
- Test A

prod3 469 e 470

---

app/commands/tickets/collect_by_external_ids.rb
app/commands/tickets/donate.rb
app/commands/vouchers/donate.rb
app/jobs/vouchers/webhook_job.rb
spec/commands/tickets/donate_spec.rb
spec/commands/vouchers/donate_spec.rb
spec/jobs/vouchers/webhook_job_spec.rb

- added WebhookJob event for dnn
- Test A

pro 535: added WebhookJob event for dnn

---

app/commands/tickets/can_collect_by_coupon_id.rb
app/commands/tickets/collect_by_coupon_id.rb
app/models/coupon.rb
app/models/ticket.rb
app/models/user_coupon.rb
config/locales/en.yml
config/locales/pt-BR.yml
db/migrate/20240415162143_add_platform_to_user_coupon.rb
db/schema.rb
spec/commands/tickets/can_collect_by_coupon_id_spec.rb
spec/commands/tickets/collect_by_coupon_id_spec.rb
spec/factories/user_coupons.rb
spec/models/user_coupon_spec.rb

- collect by coupon id command
```
user = User.last
coupon = Coupon.last
Tickets::CollectByCouponId.call(user: user, platform: "web", coupon_id: coupon.id)
```

Prod3 472: collect by coupon id command

---

app/controllers/api/v1/donations_controller.rb
app/controllers/api/v1/payments/credit_cards_controller.rb
app/controllers/api/v1/payments/cryptocurrency_controller.rb
app/controllers/api/v1/payments/pix_controller.rb
app/controllers/api/v1/payments/stores_controller.rb
app/controllers/api/v1/tickets/collect_and_donate_controller.rb
app/controllers/api/v1/tickets/collect_controller.rb
app/controllers/api/v1/users_controller.rb
app/controllers/api/v1/vouchers/donations_controller.rb
app/controllers/users/v1/donations_controller.rb
app/controllers/users/v1/tickets/collect_controller.rb
app/controllers/users/v1/tickets/donations_controller.rb
app/controllers/users/v1/vouchers/donations_controller.rb
app/jobs/tracking/add_utm_job.rb
spec/jobs/tracking/add_utm_job_spec.rb
spec/requests/api/v1/donations_spec.rb
spec/requests/api/v1/payments/credit_cards_spec.rb
spec/requests/api/v1/payments/cryptocurrencies_spec.rb
spec/requests/api/v1/payments/pix_spec.rb
spec/requests/api/v1/payments/stores_spec.rb
spec/requests/api/v1/tickets/collect_and_donate_controller_spec.rb
spec/requests/api/v1/tickets/collect_controller_spec.rb
spec/requests/api/v1/users_spec.rb
spec/requests/api/v1/vouchers/donations_spec.rb
spec/requests/users/v1/donations_spec.rb
spec/requests/users/v1/tickets/collect_controller_spec.rb
spec/requests/users/v1/vouchers/donations_spec.rb

- refactor AddUtm.call to AddUtmJob.perform_later
- I did this because it was taking time away from our methods and it is not something that needs to be done quickly
- Test A

chore: refactor AddUtm

---

app/commands/coupons/clear_expired_coupons.rb
app/jobs/coupons/clear_expired_coupons_job.rb
app/workers/coupons/clear_expired_coupons_worker.rb
config/schedule.yml
config/sidekiq.yml
spec/commands/coupons/clear_expired_coupons_spec.rb
spec/jobs/coupons/clear_expired_coupons_job_spec.rb
spec/workers/coupons/clear_expired_coupons_worker_spec.rb

- add job to clear expired coupons
- tests
- schedule 1x on week
- eg: closes [#PROD3-474]()

feat: add job to clear expired coupons

---

app/models/configs/ribon_config.rb

- invalidate cache on ribonConfig save
- Test A

fix: invalidate cache on ribonConfig save

---

app/commands/tickets/collect_by_external_ids.rb
app/commands/tickets/donate.rb
app/commands/vouchers/donate.rb
app/jobs/vouchers/webhook_job.rb
spec/commands/tickets/donate_spec.rb
spec/commands/vouchers/donate_spec.rb
spec/jobs/vouchers/webhook_job_spec.rb

Reverts RibonDAO/core-api#1352

Revert "pro 535: added WebhookJob event for dnn"

---

app/models/non_profits/non_profit_impact.rb

fix: invalidate_cache

---

app/jobs/tracking/add_utm_job.rb

fix: retry addUtmJob

---

config/initializers/rails_admin.rb
config/locales/admin.pt-BR.yml

- rails admin only for update users email
- Test A

Prod 575: rails admin only for update users email

---

app/controllers/api/v1/reports_controller.rb
app/controllers/managers/v1/reports_controller.rb

- Order in descending
- If changes order in app and manager

feat: adjust order of reports on manager and app

---

README.md
app/blueprints/non_profit_blueprint.rb
app/controllers/api/v1/non_profits_controller.rb
app/controllers/managers/v1/non_profits_controller.rb
app/models/non_profits/non_profit.rb
db/migrate/20240423151028_add_impact_title_and_cover_image_description_to_non_profit.rb
db/schema.rb
spec/blueprints/non_profit_blueprint_spec.rb
spec/factories/non_profits.rb
spec/models/non_profit_spec.rb

- Adds new database fields and a new attachment
- cover_image_description
- cover_image (attachment)
- impact_title
- Nothing
- No issue will be closed
- Create a non profit from the api with the new fields and the attachment

feat: adds the new fields to the ong selection

---

app/blueprints/non_profit_blueprint.rb
app/models/coupon.rb
db/schema.rb
spec/factories/coupons.rb
spec/factories/non_profits.rb
spec/models/coupon_spec.rb
spec/requests/api/v1/non_profits_spec.rb
spec/requests/managers/v1/non_profits_spec.rb

fix: lint & tests from Pedro's PR

---

app/blueprints/integration_blueprint.rb
spec/requests/api/v1/integrations_spec.rb
spec/requests/managers/v1/integrations_spec.rb
spec/requests/users/v1/integrations_spec.rb

- Expose metadata field to blueprint if is a referral integration
- Use user profile photo in order to prevent CORS issues by handling it in frontend.

feat: referral

---

app/blueprints/integration_blueprint.rb
app/controllers/users/v1/integrations_controller.rb
spec/requests/users/v1/integrations_spec.rb

- Filter branch in order to allow partners and user integrations at same time

feat: add branch check to user integrations

---

app/commands/tickets/collect_by_external_ids.rb
spec/commands/tickets/collect_by_external_ids_spec.rb

fix: max to 10 by external_ids

---

app/commands/tickets/can_collect_by_coupon_id.rb
app/controllers/api/v1/tickets/collect_controller.rb

- can collect by coupon id render
- coupon availability
- Test A

fix: can collect by coupon id render

---

app/blueprints/non_profit_blueprint.rb
app/controllers/managers/v1/non_profits_controller.rb
app/models/non_profits/non_profit.rb
db/migrate/20240508021313_add_icon_description_to_non_profit.rb
spec/blueprints/non_profit_blueprint_spec.rb
spec/factories/non_profits.rb
spec/models/non_profit_spec.rb
spec/requests/api/v1/non_profits_spec.rb
spec/requests/managers/v1/non_profits_spec.rb

- Add icon field to non profit. This create migration, changes tests and controller params.
- the most practical way to test is insert a icon to non profit in manager project

feat: add icon field to non profit model [PROD3-582]

---

app/commands/givings/payment/order_types/pix.rb

- I subscribe to club with pix again and there was no link between my person payment and my old subscription
- Test A

fix: pix subscription

---

app/jobs/tickets/generate_club_monthly_tickets_job.rb

- when this job is called the subscription was not updated yet with status active
- Test A

fix: remove club verification

---

app/blueprints/tag_blueprint.rb
app/commands/tags/upsert_tag.rb
app/controllers/managers/v1/tags_controller.rb
app/models/non_profit_tag.rb
app/models/non_profits/non_profit.rb
app/models/tag.rb
config/initializers/rails_admin.rb
config/routes.rb
db/migrate/20240514164944_create_tags.rb
db/migrate/20240515114011_create_non_profit_tags.rb
db/schema.rb
spec/commands/tags/upsert_tags_spec.rb
spec/factories/non_profit_tags.rb
spec/factories/tags.rb
spec/models/non_profit_tag_spec.rb
spec/models/tag_spec.rb
spec/requests/managers/v1/tags_spec.rb

- Create table tags
- Create non profit tags, a many to many relationship between non profit and tags
- Controller and command to upsert
- Show and list tags on manager
- Tests
- eg: closes [#PROD3-588]()
- Create a tag with non profits and non profit with tags

[PROD3-588] Create tags

---

app/blueprints/subscription_blueprint.rb
app/commands/givings/subscriptions/cancel_subscription.rb
app/models/subscription.rb

- cancel subscription status
- next payment date
- Test A

fix: cancel subscription status and next payment date

---

app/controllers/api/v1/tickets/tickets_controller.rb
spec/requests/api/v1/tickets/tickets_controller_spec.rb

- integration tickets available
- Test A

prod 599: integration tickets available

---

app/commands/tickets/collect_and_donate_by_external_ids.rb
app/commands/tickets/collect_and_donate_by_integration.rb
app/commands/tickets/donate.rb
app/controllers/users/v1/tickets/donations_controller.rb
db/schema.rb
spec/commands/tickets/donate_spec.rb
spec/requests/users/v1/tickets/donations_controller_spec.rb

- if integration_only true, only let donate tickets from integration
- Test A

Prod 604: integration_only

---

app/commands/users/increment_donation_streak.rb
app/jobs/donations/handle_post_donation_job.rb
app/workers/users/reset_everyone_donation_streak_worker.rb
config/schedule.yml
spec/commands/users/increment_donation_streak_spec.rb
spec/jobs/donations/handle_post_donation_job_spec.rb

- Add increment streak command to handle post donation job
- eg: closes [#PROD3-557]()
- Test A

fix: add increment streak to handle post donation job

---

app/commands/tickets/collect_and_donate_by_external_ids.rb
app/commands/tickets/collect_and_donate_by_integration.rb
app/commands/tickets/donate.rb
app/controllers/api/v1/tickets/donations_controller.rb
app/controllers/api/v1/tickets/tickets_controller.rb
app/controllers/users/v1/tickets/donations_controller.rb
config/routes.rb
db/schema.rb
spec/commands/tickets/donate_spec.rb
spec/requests/api/v1/tickets/donations_controller_spec.rb
spec/requests/api/v1/tickets/tickets_controller_spec.rb
spec/requests/users/v1/tickets/donations_controller_spec.rb

- changes to allow donate without being authenticated
- Test A

Dnn authentication

---

config/env.yml

fix: coupon url

---

app/commands/donations/donate.rb
app/commands/tickets/donate.rb
app/commands/users/set_last_donated_cause.rb
app/commands/users/set_user_last_donation_at.rb
app/jobs/donations/handle_post_donation_job.rb
app/jobs/users/update_donation_stats_job.rb
spec/commands/donations/donate_spec.rb
spec/commands/tickets/donate_spec.rb
spec/commands/users/set_last_donated_cause_spec.rb
spec/commands/users/set_user_last_donation_at_spec.rb
spec/jobs/donations/handle_post_donation_job_spec.rb
spec/jobs/users/update_donation_stats_job_spec.rb

- it was updating last_donation_at before check streak
- Test A

fix: increment streak

---

config/sidekiq.yml

fix: sidekiq queue

---

config/schedule.yml

- sidekiq worker name
- Test A

fix: sidekiq worker name

---

app/jobs/users/reset_donation_streak_job.rb
app/jobs/users/reset_everyone_donation_streak_job.rb
app/workers/users/reset_donation_streak_worker.rb
app/workers/users/reset_everyone_donation_streak_worker.rb
spec/jobs/users/reset_everyone_donation_streak_job_spec.rb
spec/workers/users/reset_donation_streak_worker_spec.rb
spec/workers/users/reset_everyone_donation_streak_worker_spec.rb

- the worker was returning this error: (Unsupported argument type: ActiveRecord::Relation)
- so I put the ActiveRecord::Relation inside the job
- Test A
-

fix: reset streak

---

app/models/subscription.rb
spec/models/subscription_spec.rb

fix: active from club

---

app/commands/givings/payment/create_order.rb
app/commands/givings/payment/order_types/credit_card.rb
app/commands/givings/payment/order_types/pix.rb
app/commands/givings/payment/order_types/store_pay.rb
app/commands/givings/subscriptions/cancel_subscription.rb
app/models/subscription.rb
spec/commands/givings/payment/create_order_spec.rb

- Cancel old subscriptions when a new one is created 
- closes [PROD3-607](https://ribon.atlassian.net/browse/PROD3-607)

feat: prod3-607

---

app/services/service/donations/pool_balances.rb
spec/services/service/donations/pool_balances_spec.rb

- polygon scan only allow 5 requets per second
- Test A

fix: polygon scan only allow 5 requets per second

---

app/jobs/donations/update_pool_balance_job.rb
app/services/service/donations/pool_balances.rb
app/workers/donations/update_pool_balance_worker.rb
spec/jobs/donations/update_pool_balance_job_spec.rb
spec/workers/donations/update_pool_balance_worker_spec.rb

- Added sleep in UpdatePoolBalanceJob
- Test A

Fix: polygon scan only allows 5 requests per second

---

app/blueprints/non_profit_blueprint.rb
app/models/stories/story.rb
spec/models/story_spec.rb

- Remove validation to description on storys
- Adjust return of icon to png
- eg: closes [#PROD3-646]()
- Add story without description
- Add icon png and see if background is transparent

[PROD3-646] Adjust model of stories and icon 

---

app/blueprints/non_profit_blueprint.rb

- remove resize logo
- eg: closes [#PROD3-646]()
- Add logo with size more than 150x150

fix: remove resize logo

---

app/models/warmglow_message.rb
db/migrate/20240604123115_create_warmglow_messages.rb

- add warmglow message table
- add mobility and enum
- eg: closes [#PROD3-619]()
- Create a warmglow message

feat: add warmglow message table

---

app/commands/tickets/donate.rb

- prevent duplicate vouchers problem
- Test A

fix: prevent duplicate vouchers problem

---

app/commands/contributions/create_contribution.rb
app/commands/coupons/clear_expired_coupons.rb
app/commands/subscriptions/revoke_subscription.rb
app/commands/tickets/collect_and_donate_by_external_ids.rb
app/commands/tickets/collect_and_donate_by_integration.rb
app/commands/tickets/collect_by_club.rb
app/commands/tickets/collect_by_coupon_id.rb
app/commands/tickets/donate.rb
app/models/ticket.rb
spec/commands/tickets/collect_and_donate_by_external_ids_spec.rb
spec/commands/tickets/collect_by_external_ids_spec.rb
spec/factories/tickets.rb
spec/factories/user/users.rb

- block duplicated tickets and vouchers with the same external_id
- refactor to remove unnecessary use of ActiveRecord::Base.transaction
- Test A

Prod 654: block duplicated tickets and vouchers with the same external_id

---

app/blueprints/warmglow_message_blueprint.rb
app/commands/warmglow_messages/upsert_warmglow_message.rb
app/controllers/api/v1/warmglow_messages_controller.rb
app/controllers/managers/v1/warmglow_messages_controller.rb
config/locales/en.yml
config/locales/pt-BR.yml
config/routes.rb
db/schema.rb
spec/commands/tags/upsert_tags_spec.rb
spec/commands/warmglow_messages/upsert_warmglow_message.rb
spec/commands/warmglow_messages/upsert_warmglow_message_spec.rb
spec/factories/warmglow_messages.rb
spec/requests/api/v1/warmglow_messages_spec.rb
spec/requests/managers/v1/warmglow_messages_spec.rb

- Random warmglow message
- If isn't a random warmglow message, returns a default
- eg: closes [#PROD3-623]()

[PROD3-623] Random warmglow message

---

app/commands/tickets/donate.rb

- Added transact donation that I removed without realizing
- removed associate_integration_vouchers from transact
- Test A

fix: added transact

---

app/controllers/api/v1/non_profits_controller.rb

fix: remove shuffle

---

app/controllers/users/v1/integrations_controller.rb
spec/requests/users/v1/integrations_spec.rb

- Prevents user to have 2 or more integrations with same branch.

fix: prevent user to have 2 integrations with same branch

---

app/commands/tickets/donate.rb
spec/commands/tickets/donate_spec.rb

- donate tickets with external_id first to prevent errors with dnn
- Test A

fix: donate tickets with external_id first

---

app/commands/tickets/can_collect_by_external_ids.rb
app/controllers/api/v1/tickets/collect_controller.rb
spec/commands/tickets/can_collect_by_external_ids_spec.rb
spec/requests/api/v1/tickets/collect_controller_spec.rb

- return tickets quantity on can collect by external ids
- Test A

feat: return tickets quantity on can collect by external ids

---

app/commands/givings/payment/order_types/credit_card.rb
app/commands/givings/payment/order_types/pix.rb
app/commands/givings/payment/order_types/store_pay.rb

fix: payment failed subscriptions

---

app/controllers/api/v1/users/subscriptions_controller.rb

- order subscriptions by created_at to fix this:
- Test A

fix: order subscriptions by created_at

---

app/commands/givings/subscriptions/create_direct_transfer_subscription.rb
app/commands/tickets/collect_by_business.rb
app/controllers/users/v1/tickets/collect_controller.rb
app/models/ticket.rb
config/routes.rb
spec/requests/users/v1/tickets/collect_controller_spec.rb

- Adds collect_by_business method
- [#prod3-705](https://ribon.atlassian.net/browse/PROD3-705)

feat: adds collect_by_business

---

app/models/payment/offer.rb
app/queries/user_queries.rb
spec/queries/user_queries_spec.rb
spec/requests/api/v1/users_spec.rb

- Add category business to offer
- Adjust tests
- Add condition to search just for category business
- eg: closes [#PROD3-686](https://ribon.atlassian.net/jira/software/c/projects/PROD3/boards/28?selectedIssue=PROD3-686)

[PROD3-686] Add category business to offer

---

app/blueprints/offer_blueprint.rb
app/models/payment/offer.rb

- Fix inactive plans on manager are not showing
- Create a offer with plan inactive

fix:  inactive plans on manager are not showing

---

app/jobs/givings/payment/add_giving_cause_to_blockchain_job.rb
app/jobs/givings/payment/add_giving_non_profit_to_blockchain_job.rb

fix: add retry limit to jobs

---

app/helpers/images_helper.rb

fix: cdn fallback
